use serde::{Deserialize, Serialize};

use crate::dsl::{BoostDuration, CardId, DamageType, Effect};
use crate::rules::run::ServerId;
use crate::rules::state::Side;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum GameEvent {
    ClickSpent { side: Side },
    CreditsGained { side: Side, amount: u32 },
    CardDrawn { side: Side },
    IceApproached { server: ServerId, position: u32 },
    IceEncountered { card_id: CardId, strength: i32, subroutine_count: usize },
    SubroutineBroken { card_id: CardId, index: usize },
    SubroutineFired { card_id: CardId, index: usize, effect: Effect },
    IceStrengthModified { card_id: CardId, new_strength: i32, delta: i32 },
    IcePassed { server: ServerId, position: u32 },
    RunSucceeded { server: ServerId },
    RunJackedOut { server: ServerId },
    RunCompleted { server: ServerId },
    CardInstalled { side: Side, card: CardId, server: ServerId },
    IceRezzed { card: CardId, server: ServerId },
    RunInitiated { server: ServerId },
    EventPlayed { side: Side, card: CardId },
    OperationPlayed { side: Side, card: CardId },
    HardwareInstalled { side: Side, card: CardId },
    ProgramInstalled { side: Side, card: CardId, memory_cost: u8 },
    CardAccessed { card: CardId, server: ServerId },
    TurnEnded { side: Side },
    TurnStarted { side: Side, clicks: u32 },
    DiscardPending { side: Side, required: usize },
    CardDiscarded { side: Side, card: CardId },
    AgendaStolen { card: CardId, agenda_points: u32 },
    DamageTaken { damage_type: DamageType, amount: usize },
    RunnerFlatlined,
    CreditsSpent { side: Side, amount: u32 },
    TagsGiven { side: Side, amount: u32 },
    TagsPurged { side: Side },
    CardTrashed { side: Side, card: CardId },
    RunEndedByEffect { server: ServerId },
    GameOver { winner: Side },
    AbilityActivated { side: Side, card_id: CardId, ability_index: usize },
    CardAdvanced { card: CardId, advancement_tokens: u32 },
    CardTrashedFromAccess { card: CardId, cost_paid: u32 },
    AccessPassed { card: CardId },
    PaidAbilityWindowOpened { side: Side },
    PriorityPassed { side: Side },
    PaidAbilityWindowClosed,
    StrengthBoosted { card_id: CardId, new_strength: i32, delta: i32, duration: BoostDuration },
    TraceInitiated { base: u32, initiating_card: Option<CardId> },
    TraceCorpBidSubmitted { corp_bid: u32, total_strength: u32 },
    TraceRunnerBidSubmitted { runner_bid: u32, total_strength: u32 },
    TraceAvoided { corp_total: u32, runner_total: u32 },
    TraceSuccessful { corp_total: u32, runner_total: u32 },
    TagRemoved { side: Side },
    TagsRemoved { side: Side, amount: u32 },
    BadPublicityCreditsSpent { amount: u32 },
    BadPublicityGiven { amount: u32 },
    BadPublicityRemoved { amount: u32 },
    HandKept { side: Side },
    MulliganTaken { side: Side },
    AdditionalAccessGranted { server: ServerId, count: u32 },
    AccessReplacementSet { server: ServerId },
    AccessReplaced { server: ServerId },
    CreditsLost { side: Side, amount: u32 },
    ClicksLost { side: Side, amount: u32 },
    RecurringCreditsSpent { amount: u32 },
    AgendaScored { card: CardId, agenda_points: u32 },
}
