//! The unbuilt cards of every set the NSG card-pool plan builds
//! (docs/roadmap/nsg-card-pool.md), one list per set, for the set gates in
//! `embedded::catalog_join_tests` — the lists `SG_UNIMPLEMENTED` and
//! `ELEV_UNIMPLEMENTED` were for their sets.
//!
//! **Every entry's reason is the same, so it is said once per list:** the
//! card is not built yet, and the list's doc comment names the tranche that
//! builds it. An entry is the card's id and its title — the title so a
//! stale entry, left behind after its card landed, names itself when the
//! gate fails. **The lists only shrink.** A card file cannot land without
//! deleting its entries, in every set that prints it (a reprint is in two
//! lists), because the gate counts a printing as built when a playable card
//! has its card's id.
//!
//! Seeded by `scripts/catalog_sync.py --unimplemented <set>` when the packs
//! were embedded (Stage 0, 26 September 2026); keyed by printing code until
//! the catalog moved to NetrunnerDB v3 (Stage 0d).

/// The formats whose whole card pool is built, held by
/// `every_card_in_a_complete_formats_pool_is_built_and_playable`: every
/// card in the format's pool is a playable card. **The list only grows**, and it grows only there: a format that
/// is not on it must still be short of a card (the same gate says so), so
/// the day Standard's last pack lands, Standard is added here or the gate
/// names it. Startup was verified complete on 29 September 2026 (Phase 5
/// §25 Stage 0): System Gateway, Elevation and Vantage Point, 225 cards.
pub(crate) const COMPLETE_FORMATS: &[crate::format::NsgFormat] = &[crate::format::NsgFormat::Startup];

/// *Vantage Point* (`vantage_point`): tranche 1 of the NSG plan.
pub(crate) const VP_UNIMPLEMENTED: &[(&str, &str)] = &[];

/// *Rebellion Without Rehearsal* (`rebellion_without_rehearsal`): tranche 2 of the NSG plan.
pub(crate) const RWR_UNIMPLEMENTED: &[(&str, &str)] = &[];

/// *The Automata Initiative* (`the_automata_initiative`): tranche 3 of the NSG plan.
pub(crate) const TAI_UNIMPLEMENTED: &[(&str, &str)] = &[
];

/// *Parhelion* (`parhelion`): tranche 4 of the NSG plan.
pub(crate) const PH_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("raindrops_cut_stone", "Raindrops Cut Stone"),
    ("time_bomb", "Time Bomb"),
    ("abaasy", "Abaasy"),
    ("hush", "Hush"),
    ("tsakhia_bankhar_gantulga", "Tsakhia \"Bankhar\" Gantulga"),
    ("concerto", "Concerto"),
    ("reprise", "Reprise"),
    ("poison_vial", "Poison Vial"),
    ("wake_implant_v2a_jrj", "WAKE Implant v2A-JRJ"),
    ("tremolo", "Tremolo"),
    ("tunnel_vision", "Tunnel Vision"),
    ("asmund_pudlat", "Asmund Pudlat"),
    ("info_bounty", "Info Bounty"),
    ("spark_of_inspiration", "Spark of Inspiration"),
    ("basilar_synthgland_2kvj", "Basilar Synthgland 2KVJ"),
    ("flux_capacitor", "Flux Capacitor"),
    ("nanuq", "Nanuq"),
    ("orca", "Orca"),
    ("k2cp_turbine", "K2CP Turbine"),
    ("world_tree", "World Tree"),
    ("nova_initiumia_catalyst_impetus", "Nova Initiumia: Catalyst & Impetus"),
    ("matryoshka", "Matryoshka"),
    ("nightmare_archive", "Nightmare Archive"),
    ("issuaq_adaptics_sustaining_diversity", "Issuaq Adaptics: Sustaining Diversity"),
    ("hybrid_release", "Hybrid Release"),
    ("dr_vientiane_keeling", "Dr. Vientiane Keeling"),
    ("hafrun", "Hafrún"),
    ("nanisivik_grid", "Nanisivik Grid"),
    ("klevetnik", "Klevetnik"),
    ("unsmiling_tsarevna", "Unsmiling Tsarevna"),
    ("kimberlite_field", "Kimberlite Field"),
    ("superdeep_borehole", "Superdeep Borehole"),
    ("anvil", "Anvil"),
    ("yakov_erikovich_avdakov", "Yakov Erikovich Avdakov"),
    ("zato_city_grid", "ZATO City Grid"),
    ("ampere_cybernetics_for_anyone", "Ampère: Cybernetics For Anyone"),
];

/// *Midnight Sun Booster Pack* (`midnight_sun_booster_pack`): tranche 5 of the NSG plan.
pub(crate) const MSBP_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("light_the_fire", "Light the Fire!"),
    ("revolver", "Revolver"),
    ("deep_dive", "Deep Dive"),
    ("hakarl_1_0", "Hákarl 1.0"),
    ("anemone", "Anemone"),
    ("vladisibirsk_city_grid", "Vladisibirsk City Grid"),
    ("azef_protocol", "Azef Protocol"),
];

/// *Midnight Sun* (`midnight_sun`): tranche 5 of the NSG plan.
pub(crate) const MS_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("esa_afontov_eco_insurrectionist", "Esâ Afontov: Eco-Insurrectionist"),
    ("chastushka", "Chastushka"),
    ("running_hot", "Running Hot"),
    ("steelskin_scarring", "Steelskin Scarring"),
    ("ghosttongue", "Ghosttongue"),
    ("marrow", "Marrow"),
    ("begemot", "Begemot"),
    ("avgustina_ivanovskaya", "Avgustina Ivanovskaya"),
    ("light_the_fire", "Light the Fire!"),
    ("the_twinning", "The Twinning"),
    ("nyusha_sable_sintashta_symphonic_prodigy", "Nyusha \"Sable\" Sintashta: Symphonic Prodigy"),
    ("carpe_diem", "Carpe Diem"),
    ("pinhole_threading", "Pinhole Threading"),
    ("pan_weave", "PAN-Weave"),
    ("virtuoso", "Virtuoso"),
    ("cats_cradle", "Cat's Cradle"),
    ("cezve", "Cezve"),
    ("revolver", "Revolver"),
    ("backstitching", "Backstitching"),
    ("no_free_lunch", "No Free Lunch"),
    ("captain_padma_isbister_intrepid_explorer", "Captain Padma Isbister: Intrepid Explorer"),
    ("deep_dive", "Deep Dive"),
    ("into_the_depths", "Into the Depths"),
    ("rigging_up", "Rigging Up"),
    ("endurance", "Endurance"),
    ("hyperbaric", "Hyperbaric"),
    ("propeller", "Propeller"),
    ("daeg_first_net_cat", "Daeg, First Net-Cat"),
    ("environmental_testing", "Environmental Testing"),
    ("stoneship_chart_room", "Stoneship Chart Room"),
    ("elivagar_bifurcation", "Élivágar Bifurcation"),
    ("midnight_3_arcology", "Midnight-3 Arcology"),
    ("refuge_campaign", "Refuge Campaign"),
    ("trieste_model_bioroids", "Trieste Model Bioroids"),
    ("echo", "Echo"),
    ("hakarl_1_0", "Hákarl 1.0"),
    ("wave", "Wave"),
    ("big_deal", "Big Deal"),
    ("blood_in_the_water", "Blood in the Water"),
    ("regenesis", "Regenesis"),
    ("bladderwort", "Bladderwort"),
    ("moon_pool", "Moon Pool"),
    ("anemone", "Anemone"),
    ("bathynomus", "Bathynomus"),
    ("ivik", "Ivik"),
    ("mitosis", "Mitosis"),
    ("mavirus", "Mavirus"),
    ("pravdivost_consulting_political_solutions", "Pravdivost Consulting: Political Solutions"),
    ("artificial_cryptocrash", "Artificial Cryptocrash"),
    ("chekist_scion", "Chekist Scion"),
    ("drago_ivanov", "Drago Ivanov"),
    ("ubiquitous_vig", "Ubiquitous Vig"),
    ("mestnichestvo", "Mestnichestvo"),
    ("vasilisa", "Vasilisa"),
    ("backroom_machinations", "Backroom Machinations"),
    ("vladisibirsk_city_grid", "Vladisibirsk City Grid"),
    ("ob_superheavy_logistics_extract_export_excel", "Ob Superheavy Logistics: Extract. Export. Excel."),
    ("azef_protocol", "Azef Protocol"),
    ("svyatogor_excavator", "Svyatogor Excavator"),
    ("envelopment", "Envelopment"),
    ("maskirovka", "Maskirovka"),
    ("stavka", "Stavka"),
    ("extract", "Extract"),
    ("mutually_assured_destruction", "Mutually Assured Destruction"),
    ("trust_operation", "Trust Operation"),
];

/// *Uprising Booster Pack* (`uprising_booster_pack`): tranche 6 of the NSG plan.
pub(crate) const URBP_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("mystic_maemi", "Mystic Maemi"),
    ("swift", "Swift"),
    ("cybertrooper_talut", "Cybertrooper Talut"),
    ("megaprix_qualifier", "Megaprix Qualifier"),
    ("la_costa_grid", "La Costa Grid"),
    ("digital_rights_management", "Digital Rights Management"),
    ("cayambe_grid", "Cayambe Grid"),
];

/// *Uprising* (`uprising`): tranche 6 of the NSG plan.
pub(crate) const UR_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("hoshiko_shiro_untold_protagonist", "Hoshiko Shiro: Untold Protagonist"),
    ("moshing", "Moshing"),
    ("devil_charm", "Devil Charm"),
    ("gachapon", "Gachapon"),
    ("keiko", "Keiko"),
    ("odore", "Odore"),
    ("mystic_maemi", "Mystic Maemi"),
    ("paladin_poemu", "Paladin Poemu"),
    ("bravado", "Bravado"),
    ("boomerang", "Boomerang"),
    ("mu_safecracker", "Mu Safecracker"),
    ("prognostic_q_loop", "Prognostic Q-Loop"),
    ("swift", "Swift"),
    ("afterimage", "Afterimage"),
    ("makler", "Makler"),
    ("penumbral_toolkit", "Penumbral Toolkit"),
    ("the_back", "The Back"),
    ("harmony_ar_therapy", "Harmony AR Therapy"),
    ("aniccam", "Aniccam"),
    ("simulchip", "Simulchip"),
    ("cordyceps", "Cordyceps"),
    ("euler", "Euler"),
    ("mantle", "Mantle"),
    ("penrose", "Penrose"),
    ("self_modifying_code", "Self-modifying Code"),
    ("cybertrooper_talut", "Cybertrooper Talut"),
    ("paules_cafe", "Pauleʼs Café"),
    ("buffer_drive", "Buffer Drive"),
    ("daily_casts", "Daily Casts"),
    ("dreamnet", "DreamNet"),
    ("megaprix_qualifier", "Megaprix Qualifier"),
    ("project_vacheron", "Project Vacheron"),
    ("bass_ch1r180g4", "Bass CH1R180G4"),
    ("cerebral_overwriter", "Cerebral Overwriter"),
    ("vaporframe_fabricator", "Vaporframe Fabricator"),
    ("drafter", "Drafter"),
    ("tyr", "Týr"),
    ("next_activation_command", "NEXT Activation Command"),
    ("scapenet", "Scapenet"),
    ("tranquility_home_grid", "Tranquility Home Grid"),
    ("flower_sermon", "Flower Sermon"),
    ("prana_condenser", "Prāna Condenser"),
    ("engram_flush", "Engram Flush"),
    ("konjin", "Konjin"),
    ("hyoubu_precog_manifold", "Hyoubu Precog Manifold"),
    ("kakurenbo", "Kakurenbo"),
    ("la_costa_grid", "La Costa Grid"),
    ("gamenet_where_dreams_are_real", "GameNET: Where Dreams are Real"),
    ("bellona", "Bellona"),
    ("f2p", "F2P"),
    ("gold_farmer", "Gold Farmer"),
    ("digital_rights_management", "Digital Rights Management"),
    ("sync_rerouting", "SYNC Rerouting"),
    ("ganked", "Ganked!"),
    ("earth_station_sea_headquarters", "Earth Station: SEA Headquarters"),
    ("transport_monopoly", "Transport Monopoly"),
    ("wall_to_wall", "Wall to Wall"),
    ("akhet", "Akhet"),
    ("colossus", "Colossus"),
    ("winchester", "Winchester"),
    ("argus_crackdown", "Argus Crackdown"),
    ("cayambe_grid", "Cayambe Grid"),
    ("cyberdex_sandbox", "Cyberdex Sandbox"),
    ("false_lead", "False Lead"),
    ("napd_cordon", "NAPD Cordon"),
];

/// *Downfall* (`downfall`): tranche 7 of the NSG plan.
pub(crate) const DF_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("isolation", "Isolation"),
    ("demolisher", "Demolisher"),
    ("chisel", "Chisel"),
    ("stargate", "Stargate"),
    ("utae", "Utae"),
    ("climactic_showdown", "Climactic Showdown"),
    ("fencer_fueno", "Fencer Fueno"),
    ("the_nihilist", "The Nihilist"),
    ("trickster_taka", "Trickster Taka"),
    ("az_mccaffrey_mechanical_prodigy", "Az McCaffrey: Mechanical Prodigy"),
    ("always_have_a_backup_plan", "Always Have a Backup Plan"),
    ("blueberry_diesel", "Blueberry!™ Diesel"),
    ("flip_switch", "Flip Switch"),
    ("lucky_charm", "Lucky Charm"),
    ("masterwork_v37", "Masterwork (v37)"),
    ("bukhgalter", "Bukhgalter"),
    ("baklan_bochkin", "“Baklan” Bochkin"),
    ("the_class_act", "The Class Act"),
    ("lat_ethical_freelancer", "Lat: Ethical Freelancer"),
    ("in_the_groove", "In the Groove"),
    ("khusyuk", "Khusyuk"),
    ("spec_work", "Spec Work"),
    ("supercorridor", "Supercorridor"),
    ("gauss", "Gauss"),
    ("pelangi", "Pelangi"),
    ("rezeki", "Rezeki"),
    ("the_artist", "The Artist"),
    ("direct_access", "Direct Access"),
    ("rejig", "Rejig"),
    ("whistleblower", "Whistleblower"),
    ("mirrormorph_endless_iteration", "MirrorMorph: Endless Iteration"),
    ("architect_deployment_test", "Architect Deployment Test"),
    ("calvin_b4l3y", "Calvin B4L3Y"),
    ("nanoetching_matrix", "Nanoetching Matrix"),
    ("hagen", "Hagen"),
    ("fully_operational", "Fully Operational"),
    ("red_level_clearance", "Red Level Clearance"),
    ("cold_site_server", "Cold Site Server"),
    ("hyoubu_institute_absolute_clarity", "Hyoubu Institute: Absolute Clarity"),
    ("project_yagi_uda", "Project Yagi-Uda"),
    ("sting", "Sting!"),
    ("public_health_portal", "Public Health Portal"),
    ("storgotic_resonator", "Storgotic Resonator"),
    ("saisentan", "Saisentan"),
    ("complete_image", "Complete Image"),
    ("letheia_nisei", "Letheia Nisei"),
    ("remastered_edition", "Remastered Edition"),
    ("daily_quest", "Daily Quest"),
    ("tiered_subscription", "Tiered Subscription"),
    ("congratulations", "Congratulations!"),
    ("loot_box", "Loot Box"),
    ("focus_group", "Focus Group"),
    ("game_over", "Game Over"),
    ("increased_drop_rates", "Increased Drop Rates"),
    ("divested_trust", "Divested Trust"),
    ("sds_drone_deployment", "SDS Drone Deployment"),
    ("roughneck_repair_squad", "Roughneck Repair Squad"),
    ("afshar", "Afshar"),
    ("sandstone", "Sandstone"),
    ("trebuchet", "Trebuchet"),
    ("secure_and_protect", "Secure and Protect"),
    ("reduced_service", "Reduced Service"),
    ("vulnerability_audit", "Vulnerability Audit"),
    ("csr_campaign", "CSR Campaign"),
    ("rime", "Rime"),
];

/// *System Update 2021* (`system_update_2021`): tranche 8 of the NSG plan.
pub(crate) const SU21_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("quetzal_free_spirit", "Quetzal: Free Spirit"),
    ("reina_roja_freedom_fighter", "Reina Roja: Freedom Fighter"),
    ("en_passant", "En Passant"),
    ("retrieval_run", "Retrieval Run"),
    ("clot", "Clot"),
    ("imp", "Imp"),
    ("mimic", "Mimic"),
    ("ice_carver", "Ice Carver"),
    ("liberated_account", "Liberated Account"),
    ("scrubber", "Scrubber"),
    ("xanadu", "Xanadu"),
    ("ken_express_tenma_disappeared_clone", "Ken “Express” Tenma: Disappeared Clone"),
    ("steve_cambridge_master_grifter", "Steve Cambridge: Master Grifter"),
    ("career_fair", "Career Fair"),
    ("emergency_shutdown", "Emergency Shutdown"),
    ("forged_activation_orders", "Forged Activation Orders"),
    ("inside_job", "Inside Job"),
    ("legwork", "Legwork"),
    ("networking", "Networking"),
    ("abagnale", "Abagnale"),
    ("femme_fatale", "Femme Fatale"),
    ("sneakdoor_beta", "Sneakdoor Beta"),
    ("security_testing", "Security Testing"),
    ("ayla_bios_rahim_simulant_specialist", "Ayla “Bios” Rahim: Simulant Specialist"),
    ("rielle_kit_peddler_transhuman", "Rielle “Kit” Peddler: Transhuman"),
    ("test_run", "Test Run"),
    ("atman", "Atman"),
    ("chameleon", "Chameleon"),
    ("egret", "Egret"),
    ("paricia", "Paricia"),
    ("aesops_pawnshop", "Aesop’s Pawnshop"),
    ("professional_contacts", "Professional Contacts"),
    ("dirty_laundry", "Dirty Laundry"),
    ("prepaid_voicepad", "Prepaid VoicePAD"),
    ("earthrise_hotel", "Earthrise Hotel"),
    ("haas_bioroid_architects_of_tomorrow", "Haas-Bioroid: Architects of Tomorrow"),
    ("project_vitruvius", "Project Vitruvius"),
    ("marilyn_campaign", "Marilyn Campaign"),
    ("eli_1_0", "Eli 1.0"),
    ("magnet", "Magnet"),
    ("ravana_1_0", "Ravana 1.0"),
    ("rototurret", "Rototurret"),
    ("archived_memories", "Archived Memories"),
    ("biotic_labor", "Biotic Labor"),
    ("corporate_troubleshooter", "Corporate Troubleshooter"),
    ("house_of_knives", "House of Knives"),
    ("nisei_mk_ii", "Nisei MK II"),
    ("ronin", "Ronin"),
    ("lotus_field", "Lotus Field"),
    ("swordsman", "Swordsman"),
    ("celebrity_gift", "Celebrity Gift"),
    ("trick_of_light", "Trick of Light"),
    ("hokusai_grid", "Hokusai Grid"),
    ("near_earth_hub_broadcast_center", "Near-Earth Hub: Broadcast Center"),
    ("license_acquisition", "License Acquisition"),
    ("project_beale", "Project Beale"),
    ("daily_business_show", "Daily Business Show"),
    ("reversed_accounts", "Reversed Accounts"),
    ("pop_up_window", "Pop-up Window"),
    ("tollbooth", "Tollbooth"),
    ("wraparound", "Wraparound"),
    ("psychographics", "Psychographics"),
    ("sansan_city_grid", "SanSan City Grid"),
    ("oaktown_renovation", "Oaktown Renovation"),
    ("project_atlas", "Project Atlas"),
    ("corporate_town", "Corporate Town"),
    ("archer", "Archer"),
    ("hortum", "Hortum"),
    ("punitive_counterstrike", "Punitive Counterstrike"),
    ("crisium_grid", "Crisium Grid"),
    ("subliminal_messaging", "Subliminal Messaging"),
];

/// *Salvaged Memories* (`salvaged_memories`): tranche 8 of the NSG plan.
pub(crate) const SM_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("medium", "Medium"),
    ("parasite", "Parasite"),
    ("e3_feedback_implants", "e3 Feedback Implants"),
    ("cache", "Cache"),
    ("indexing", "Indexing"),
    ("cerberus_lady_h1", "Cerberus \"Lady\" H1"),
    ("lucky_find", "Lucky Find"),
    ("prepaid_voicepad", "Prepaid VoicePAD"),
    ("next_bronze", "NEXT Bronze"),
    ("next_silver", "NEXT Silver"),
    ("hostile_infrastructure", "Hostile Infrastructure"),
    ("turtlebacks", "Turtlebacks"),
    ("sweeps_week", "Sweeps Week"),
    ("sansan_city_grid", "SanSan City Grid"),
    ("executive_boot_camp", "Executive Boot Camp"),
    ("excalibur", "Excalibur"),
    ("subliminal_messaging", "Subliminal Messaging"),
];

/// *Magnum Opus Reprint* (`magnum_opus_reprint`): tranche 8 of the NSG plan.
pub(crate) const MOR_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("labor_rights", "Labor Rights"),
    ("crowdfunding", "Crowdfunding"),
    ("embolus", "Embolus"),
    ("slot_machine", "Slot Machine"),
    ("border_control", "Border Control"),
    ("timely_public_release", "Timely Public Release"),
];
