//! The unbuilt cards of every set the NSG card-pool plan builds
//! (docs/roadmap/nsg-card-pool.md), one list per set, for the set gates in
//! `embedded::catalog_join_tests` — the lists `SG_UNIMPLEMENTED` and
//! `ELEV_UNIMPLEMENTED` were for their sets.
//!
//! **Every entry's reason is the same, so it is said once per list:** the
//! card is not built yet, and the list's doc comment names the tranche that
//! builds it. An entry is the card's id and its title — the title so a
//! stale entry, left behind after its card landed, names itself when the
//! gate fails. **The lists only shrink.** A card file cannot land without
//! deleting its entries, in every set that prints it (a reprint is in two
//! lists), because the gate counts a printing as built when a playable card
//! has its card's id.
//!
//! Seeded by `scripts/catalog_sync.py --unimplemented <set>` when the packs
//! were embedded (Stage 0, 26 September 2026); keyed by printing code until
//! the catalog moved to NetrunnerDB v3 (Stage 0d).

/// The formats whose whole card pool is built, held by
/// `every_card_in_a_complete_formats_pool_is_built_and_playable`: every
/// card in the format's pool is a playable card. **The list only grows**, and it grows only there: a format that
/// is not on it must still be short of a card (the same gate says so), so
/// the day Standard's last pack lands, Standard is added here or the gate
/// names it. Startup was verified complete on 29 September 2026 (Phase 5
/// §25 Stage 0): System Gateway, Elevation and Vantage Point, 225 cards.
/// Standard was, with Downfall Stage 8 (6 October 2026): its last unbuilt
/// cards were Downfall's.
pub(crate) const COMPLETE_FORMATS: &[crate::format::NsgFormat] = &[crate::format::NsgFormat::Startup, crate::format::NsgFormat::Standard];

/// *Vantage Point* (`vantage_point`): tranche 1 of the NSG plan.
pub(crate) const VP_UNIMPLEMENTED: &[(&str, &str)] = &[];

/// *Rebellion Without Rehearsal* (`rebellion_without_rehearsal`): tranche 2 of the NSG plan.
pub(crate) const RWR_UNIMPLEMENTED: &[(&str, &str)] = &[];

/// *The Automata Initiative* (`the_automata_initiative`): tranche 3 of the NSG plan.
pub(crate) const TAI_UNIMPLEMENTED: &[(&str, &str)] = &[
];

/// *Parhelion* (`parhelion`): tranche 4 of the NSG plan.
pub(crate) const PH_UNIMPLEMENTED: &[(&str, &str)] = &[];

/// *Midnight Sun Booster Pack* (`midnight_sun_booster_pack`): tranche 5 of the NSG plan.
pub(crate) const MSBP_UNIMPLEMENTED: &[(&str, &str)] = &[];

/// *Midnight Sun* (`midnight_sun`): tranche 5 of the NSG plan.
pub(crate) const MS_UNIMPLEMENTED: &[(&str, &str)] = &[];

/// *Uprising Booster Pack* (`uprising_booster_pack`): tranche 6 of the NSG plan.
pub(crate) const URBP_UNIMPLEMENTED: &[(&str, &str)] = &[];

/// *Uprising* (`uprising`): tranche 6 of the NSG plan.
pub(crate) const UR_UNIMPLEMENTED: &[(&str, &str)] = &[];

/// *Downfall* (`downfall`): tranche 7 of the NSG plan.
pub(crate) const DF_UNIMPLEMENTED: &[(&str, &str)] = &[];

/// *System Update 2021* (`system_update_2021`): tranche 8 of the NSG plan.
pub(crate) const SU21_UNIMPLEMENTED: &[(&str, &str)] = &[];

/// *Salvaged Memories* (`salvaged_memories`): tranche 8 of the NSG plan.
pub(crate) const SM_UNIMPLEMENTED: &[(&str, &str)] = &[];

/// *Magnum Opus Reprint* (`magnum_opus_reprint`): tranche 8 of the NSG plan.
pub(crate) const MOR_UNIMPLEMENTED: &[(&str, &str)] = &[];

/// The *Core Set* (`core_set`): its reprinted cards were built with their
/// reprints and the rest by tranche 8 Stage 11, so it was gated (Stage 11x)
/// only once every card was built; a catalog sync that changes its list
/// now fails here.
pub(crate) const CORE_UNIMPLEMENTED: &[(&str, &str)] = &[];

// The Fantasy Flight Games sets (docs/roadmap/ffg-card-pool.md), embedded by
// its Stage 0a with every card they add listed here, in printing order, so
// each list only shrinks as the tranches build them. A card two of these
// sets print is listed in both. Written from the committed catalog the way
// `scripts/catalog_sync.py --unimplemented <set id>` writes one set.

/// *Revised Core Set* (`revised_core_set`): tranche F1 of the FFG plan.
pub(crate) const CORE2_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("singularity", "Singularity"),
    ("spinal_modem", "Spinal Modem"),
    ("darwin", "Darwin"),
    ("force_of_nature", "Force of Nature"),
    ("hemorrhage", "Hemorrhage"),
    ("morning_star", "Morning Star"),
    ("doppelganger", "Doppelgänger"),
    ("hq_interface", "HQ Interface"),
    ("faerie", "Faerie"),
    ("peacock", "Peacock"),
    ("pheromones", "Pheromones"),
    ("fall_guy", "Fall Guy"),
    ("mr_li", "Mr. Li"),
    ("chaos_theory_wunderkind", "Chaos Theory: Wünderkind"),
    ("notoriety", "Notoriety"),
    ("dinosaurus", "Dinosaurus"),
    ("all_nighter", "All-nighter"),
    ("dyson_mem_chip", "Dyson Mem Chip"),
    ("underworld_contact", "Underworld Contact"),
    ("haas_bioroid_stronger_together", "Haas-Bioroid: Stronger Together"),
    ("project_ares", "Project Ares"),
    ("hudson_1_0", "Hudson 1.0"),
    ("green_level_clearance", "Green Level Clearance"),
    ("ash_2x3zb9cy", "Ash 2X3ZB9CY"),
    ("strongbox", "Strongbox"),
    ("the_cleaners", "The Cleaners"),
    ("dedicated_response_team", "Dedicated Response Team"),
    ("elizabeth_mills", "Elizabeth Mills"),
    ("grndl_refinery", "GRNDL Refinery"),
    ("caduceus", "Caduceus"),
    ("hive", "Hive"),
    ("braintrust", "Braintrust"),
    ("himitsu_bako", "Himitsu-Bako"),
    ("whirlpool", "Whirlpool"),
    ("yagura", "Yagura"),
    ("tgtbt", "TGTBT"),
    ("flare", "Flare"),
    ("bernice_mai", "Bernice Mai"),
];

/// *Reign and Reverie* (`reign_and_reverie`): tranche F2 of the FFG plan.
pub(crate) const RAR_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("nathaniel_gnat_hall_one_of_a_kind", "Nathaniel \"Gnat\" Hall: One-of-a-Kind"),
    ("divide_and_conquer", "Divide and Conquer"),
    ("guinea_pig", "Guinea Pig"),
    ("patchwork", "Patchwork"),
    ("hijacked_router", "Hijacked Router"),
    ("cradle", "Cradle"),
    ("district_99", "District 99"),
    ("liza_talking_thunder_prominent_legislator", "Liza Talking Thunder: Prominent Legislator"),
    ("hot_pursuit", "Hot Pursuit"),
    ("paragon", "Paragon"),
    ("bankroll", "Bankroll"),
    ("tycoon", "Tycoon"),
    ("thunder_art_gallery", "Thunder Art Gallery"),
    ("miss_bones", "Miss Bones"),
    ("akiko_nisei_head_case", "Akiko Nisei: Head Case"),
    ("insight", "Insight"),
    ("minds_eye", "Mind's Eye"),
    ("mache", "Mâché"),
    ("ika", "Ika"),
    ("kyuban", "Kyuban"),
    ("psych_mike", "Psych Mike"),
    ("algernon", "Algernon"),
    ("reboot", "Reboot"),
    ("office_supplies", "Office Supplies"),
    ("dj_fenris", "DJ Fenris"),
    ("sportsmetal_go_big_or_go_home", "Sportsmetal: Go Big or Go Home"),
    ("hyperloop_extension", "Hyperloop Extension"),
    ("meridian", "Meridian"),
    ("gatekeeper", "Gatekeeper"),
    ("divert_power", "Divert Power"),
    ("fast_break", "Fast Break"),
    ("game_changer", "Game Changer"),
    ("giordano_memorial_field", "Giordano Memorial Field"),
    ("saraswati_mnemonics_endless_exploration", "Saraswati Mnemonics: Endless Exploration"),
    ("jumon", "Jumon"),
    ("api_s_keeper_isobel", "API-S Keeper Isobel"),
    ("neurostasis", "Neurostasis"),
    ("otoroshi", "Otoroshi"),
    ("thimblerig", "Thimblerig"),
    ("hangeki", "Hangeki"),
    ("daruma", "Daruma"),
    ("acme_consulting_the_truth_you_need", "Acme Consulting: The Truth You Need"),
    ("fly_on_the_wall", "Fly on the Wall"),
    ("siu", "SIU"),
    ("peeping_tom", "Peeping Tom"),
    ("hydra", "Hydra"),
    ("eavesdrop", "Eavesdrop"),
    ("attitude_adjustment", "Attitude Adjustment"),
    ("arella_salvatore", "Arella Salvatore"),
    ("the_outfit_family_owned_and_operated", "The Outfit: Family Owned and Operated"),
    ("broad_daylight", "Broad Daylight"),
    ("drudge_work", "Drudge Work"),
    ("blockchain", "Blockchain"),
    ("formicary", "Formicary"),
    ("building_blocks", "Building Blocks"),
    ("too_big_to_fail", "Too Big to Fail"),
    ("under_the_bus", "Under the Bus"),
    ("lady_liberty", "Lady Liberty"),
];

/// *Sovereign Sight* (`sovereign_sight`): tranche F3 of the FFG plan.
pub(crate) const SS_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("by_any_means", "By Any Means"),
    ("yusuf", "Yusuf"),
    ("zamba", "Zamba"),
    ("puffer", "Puffer"),
    ("lewi_guilherme", "Lewi Guilherme"),
    ("cyberdelia", "Cyberdelia"),
    ("upya", "Upya"),
    ("assimilator", "Assimilator"),
    ("asa_group_security_through_vigilance", "Asa Group: Security Through Vigilance"),
    ("ikawah_project", "Ikawah Project"),
    ("najja_1_0", "Najja 1.0"),
    ("gene_splicer", "Gene Splicer"),
    ("mganga", "Mganga"),
    ("genotyping", "Genotyping"),
    ("echo_chamber", "Echo Chamber"),
    ("self_growth_program", "Self-Growth Program"),
    ("calibration_testing", "Calibration Testing"),
    ("urban_renewal", "Urban Renewal"),
    ("wake_up_call", "Wake Up Call"),
    ("reconstruction_contract", "Reconstruction Contract"),
];

/// *Down the White Nile* (`down_the_white_nile`): tranche F3 of the FFG plan.
pub(crate) const DTWN_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("acacia", "Acacia"),
    ("plague", "Plague"),
    ("credit_kiting", "Credit Kiting"),
    ("wari", "Wari"),
    ("kabonesa_wu_netspace_thrillseeker", "Kabonesa Wu: Netspace Thrillseeker"),
    ("takobi", "Takobi"),
    ("kongamato", "Kongamato"),
    ("emergent_creativity", "Emergent Creativity"),
    ("rng_key", "RNG Key"),
    ("nightdancer", "Nightdancer"),
    ("jinja_city_grid", "Jinja City Grid"),
    ("aimor", "Aimor"),
    ("bacterial_programming", "Bacterial Programming"),
    ("jua", "Jua"),
    ("threat_assessment", "Threat Assessment"),
    ("economic_warfare", "Economic Warfare"),
    ("forced_connection", "Forced Connection"),
    ("ssl_endorsement", "SSL Endorsement"),
    ("ngo_front", "NGO Front"),
    ("distract_the_masses", "Distract the Masses"),
];

/// *Council of the Crest* (`council_of_the_crest`): tranche F3 of the FFG plan.
pub(crate) const COTC_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("exer", "eXer"),
    ("friday_chip", "Friday Chip"),
    ("crypt", "Crypt"),
    ("corporate_grant", "Corporate \"Grant\""),
    ("no_one_home", "No One Home"),
    ("marathon", "Marathon"),
    ("gbahali", "Gbahali"),
    ("white_hat", "White Hat"),
    ("kuwinda_k4h1u3", "Kuwinda K4H1U3"),
    ("next_sapphire", "NEXT Sapphire"),
    ("anansi", "Anansi"),
    ("code_replicator", "Code Replicator"),
    ("reverse_infection", "Reverse Infection"),
    ("azmari_edtech_shaping_the_future", "Azmari EdTech: Shaping the Future"),
    ("degree_mill", "Degree Mill"),
    ("personalized_portal", "Personalized Portal"),
    ("armed_intimidation", "Armed Intimidation"),
    ("death_and_taxes", "Death and Taxes"),
    ("trojan_horse", "Trojan Horse"),
    ("technoco", "TechnoCo"),
];

/// *The Devil and the Dragon* (`the_devil_and_the_dragon`): tranche F3 of the FFG plan.
pub(crate) const TDATD_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("glut_cipher", "Glut Cipher"),
    ("knobkierie", "Knobkierie"),
    ("419_amoral_scammer", "419: Amoral Scammer"),
    ("falsified_credentials", "Falsified Credentials"),
    ("rogue_trading", "Rogue Trading"),
    ("because_i_can", "Because I Can"),
    ("nyashia", "Nyashia"),
    ("consume", "Consume"),
    ("malia_z0l0k4", "Malia Z0L0K4"),
    ("kill_switch", "Kill Switch"),
    ("tempus", "Tempus"),
    ("bio_vault", "Bio Vault"),
    ("sadaka", "Sadaka"),
    ("endless_eula", "Endless EULA"),
    ("sandman", "Sandman"),
    ("amani_senai", "Amani Senai"),
    ("sso_industries_fueling_innovation", "SSO Industries: Fueling Innovation"),
    ("city_works_project", "City Works Project"),
    ("oduduwa", "Oduduwa"),
    ("rashida_jaheem", "Rashida Jaheem"),
];

/// *Whispers in Nalubaale* (`whispers_in_nalubaale`): tranche F3 of the FFG plan.
pub(crate) const WIN_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("freedom_khumalo_crypto_anarchist", "Freedom Khumalo: Crypto-Anarchist"),
    ("trypano", "Trypano"),
    ("contaminate", "Contaminate"),
    ("embezzle", "Embezzle"),
    ("slipstream", "Slipstream"),
    ("laamb", "Laamb"),
    ("gebrselassie", "Gebrselassie"),
    ("compile", "Compile"),
    ("logic_bomb", "Logic Bomb"),
    ("jackpot", "Jackpot!"),
    ("remote_enforcement", "Remote Enforcement"),
    ("kamali_1_0", "Kamali 1.0"),
    ("warden_fatuma", "Warden Fatuma"),
    ("viral_weaponization", "Viral Weaponization"),
    ("envelope", "Envelope"),
    ("mwanza_city_grid", "Mwanza City Grid"),
    ("standard_procedure", "Standard Procedure"),
    ("intake", "Intake"),
    ("masvingo", "Masvingo"),
    ("overseer_matrix", "Overseer Matrix"),
];

/// *Kampala Ascendent* (`kampala_ascendent`): tranche F3 of the FFG plan.
pub(crate) const KA_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("zer0", "Zer0"),
    ("musaazi", "Musaazi"),
    ("hippo", "Hippo"),
    ("amina", "Amina"),
    ("diversion_of_funds", "Diversion of Funds"),
    ("pad_tap", "PAD Tap"),
    ("reclaim", "Reclaim"),
    ("engolo", "Engolo"),
    ("flame_out", "Flame-out"),
    ("black_hat", "Black Hat"),
    ("kasi_string", "Kasi String"),
    ("next_diamond", "NEXT Diamond"),
    ("riot_suppression", "Riot Suppression"),
    ("mti_mwekundu_life_improved", "Mti Mwekundu: Life Improved"),
    ("mlinzi", "Mlinzi"),
    ("better_citizen_program", "Better Citizen Program"),
    ("market_forces", "Market Forces"),
    ("surveyor", "Surveyor"),
    ("high_profile_target", "High-Profile Target"),
    ("false_flag", "False Flag"),
];

/// *Daedalus Complex* (`daedalus_complex`): tranche F4 of the FFG plan.
pub(crate) const DC_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("pushing_the_envelope", "Pushing the Envelope"),
    ("maw", "Maw"),
    ("the_archivist", "The Archivist"),
    ("exploit", "Exploit"),
    ("spot_the_prey", "Spot the Prey"),
    ("bio_modeled_network", "Bio-Modeled Network"),
    ("network_exchange", "Network Exchange"),
    ("mad_dash", "Mad Dash"),
    ("next_wave_2", "NEXT Wave 2"),
    ("zed_2_0", "Zed 2.0"),
    ("defense_construct", "Defense Construct"),
    ("synth_dna_modification", "Synth DNA Modification"),
    ("kakugo", "Kakugo"),
    ("net_analytics", "Net Analytics"),
    ("sync_bre", "SYNC BRE"),
    ("jemison_astronautics_sacrifice_audacity_success", "Jemison Astronautics: Sacrifice. Audacity. Success."),
    ("quarantine_system", "Quarantine System"),
    ("oberth_protocol", "Oberth Protocol"),
    ("khondi_plaza", "Khondi Plaza"),
    ("signal_jamming", "Signal Jamming"),
];

/// *Station One* (`station_one`): tranche F4 of the FFG plan.
pub(crate) const SO_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("severnius_stim_implant", "Severnius Stim Implant"),
    ("clan_vengeance", "Clan Vengeance"),
    ("counter_surveillance", "Counter Surveillance"),
    ("mobius", "Möbius"),
    ("los_data_hijacker", "Los: Data Hijacker"),
    ("system_seizure", "System Seizure"),
    ("customized_secretary", "Customized Secretary"),
    ("build_script", "Build Script"),
    ("seidr_adaptive_barrier", "Seidr Adaptive Barrier"),
    ("nerine_2_0", "Nerine 2.0"),
    ("load_testing", "Load Testing"),
    ("bloom", "Bloom"),
    ("replanting", "Replanting"),
    ("cpc_generator", "CPC Generator"),
    ("free_lunch", "Free Lunch"),
    ("mca_informant", "MCA Informant"),
    ("clyde_van_rite", "Clyde Van Rite"),
    ("watchtower", "Watchtower"),
    ("sacrifice", "Sacrifice"),
    ("self_adapting_code_wall", "Self-Adapting Code Wall"),
];

/// *Earth's Scion* (`earths_scion`): tranche F4 of the FFG plan.
pub(crate) const EAS_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("berserker", "Berserker"),
    ("persephone", "Persephone"),
    ("rubicon_switch", "Rubicon Switch"),
    ("aeneas_informant", "Aeneas Informant"),
    ("rosetta_2_0", "Rosetta 2.0"),
    ("adjusted_matrix", "Adjusted Matrix"),
    ("dedicated_processor", "Dedicated Processor"),
    ("inversificator", "Inversificator"),
    ("dadiana_chacon", "Dadiana Chacon"),
    ("next_opal", "NEXT Opal"),
    ("bioroid_work_crew", "Bioroid Work Crew"),
    ("aginfusion_new_miracles_for_a_new_world", "AgInfusion: New Miracles for a New World"),
    ("bamboo_dome", "Bamboo Dome"),
    ("ben_musashi", "Ben Musashi"),
    ("authenticator", "Authenticator"),
    ("henry_phillips", "Henry Phillips"),
    ("battlement", "Battlement"),
    ("audacity", "Audacity"),
    ("red_planet_couriers", "Red Planet Couriers"),
    ("owl", "Owl"),
];

/// *Blood and Water* (`blood_and_water`): tranche F4 of the FFG plan.
pub(crate) const BAW_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("alice_merchant_clan_agitator", "Alice Merchant: Clan Agitator"),
    ("jarogniew_mercs", "Jarogniew Mercs"),
    ("maui", "Māui"),
    ("bug_out_bag", "Bug Out Bag"),
    ("keros_mcintyre", "Keros Mcintyre"),
    ("daredevil", "Daredevil"),
    ("mass_driver", "Mass-Driver"),
    ("warroid_tracker", "Warroid Tracker"),
    ("loki", "Loki"),
    ("obokata_protocol", "Obokata Protocol"),
    ("miraju", "Mirāju"),
    ("shipment_from_tennin", "Shipment from Tennin"),
    ("escalate_vitriol", "Escalate Vitriol"),
    ("reeducation", "Reeducation"),
    ("traffic_analyzer", "Traffic Analyzer"),
    ("meteor_mining", "Meteor Mining"),
    ("standoff", "Standoff"),
    ("success", "Success"),
    ("whampoa_reclamation", "Whampoa Reclamation"),
    ("mass_commercialization", "Mass Commercialization"),
];

/// *Free Mars* (`free_mars`): tranche F4 of the FFG plan.
pub(crate) const FM_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("mars_for_martians", "Mars for Martians"),
    ("god_of_war", "God of War"),
    ("leave_no_trace", "Leave No Trace"),
    ("rip_deal", "Rip Deal"),
    ("flashbang", "Flashbang"),
    ("lean_and_mean", "Lean and Mean"),
    ("maven", "Maven"),
    ("nanotk", "Na'Not'K"),
    ("bloo_moose", "Bloo Moose"),
    ("o_shortage", "O₂ Shortage"),
    ("helheim_servers", "Helheim Servers"),
    ("mandatory_seed_replacement", "Mandatory Seed Replacement"),
    ("water_monopoly", "Water Monopoly"),
    ("metamorph", "Metamorph"),
    ("data_loop", "Data Loop"),
    ("biased_reporting", "Biased Reporting"),
    ("open_forum", "Open Forum"),
    ("tithonium", "Tithonium"),
    ("transparency_initiative", "Transparency Initiative"),
    ("rover_algorithm", "Rover Algorithm"),
];

/// *Crimson Dust* (`crimson_dust`): tranche F4 of the FFG plan.
pub(crate) const CD_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("mining_accident", "Mining Accident"),
    ("respirocytes", "Respirocytes"),
    ("salvaged_vanadis_armory", "Salvaged Vanadis Armory"),
    ("aumakua", "Aumakua"),
    ("caldera", "Caldera"),
    ("dianas_hunt", "Diana's Hunt"),
    ("reshape", "Reshape"),
    ("dummy_box", "Dummy Box"),
    ("corporate_defector", "Corporate Defector"),
    ("cfc_excavation_contract", "CFC Excavation Contract"),
    ("mca_austerity_policy", "MCA Austerity Policy"),
    ("restore", "Restore"),
    ("breached_dome", "Breached Dome"),
    ("sand_storm", "Sand Storm"),
    ("ar_enhanced_security", "AR-Enhanced Security"),
    ("rolling_brownout", "Rolling Brownout"),
    ("threat_level_alpha", "Threat Level Alpha"),
    ("priority_construction", "Priority Construction"),
    ("fractal_threat_matrix", "Fractal Threat Matrix"),
    ("conundrum", "Conundrum"),
];

/// *23 Seconds* (`23_seconds`): tranche F5 of the FFG plan.
pub(crate) const S23S_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("system_outage", "System Outage"),
    ("null_whistleblower", "Null: Whistleblower"),
    ("gpi_net_tap", "GPI Net Tap"),
    ("hernando_cortez", "Hernando Cortez"),
    ("mirror", "Mirror"),
    ("dai_v", "Dai V"),
    ("another_day_another_paycheck", "Another Day, Another Paycheck"),
    ("deuces_wild", "Deuces Wild"),
    ("injection_attack", "Injection Attack"),
    ("fairchild_1_0", "Fairchild 1.0"),
    ("sherlock_2_0", "Sherlock 2.0"),
    ("hyoubu_research_facility", "Hyoubu Research Facility"),
    ("chrysalis", "Chrysalis"),
    ("georgia_emelyov", "Georgia Emelyov"),
    ("watchdog", "Watchdog"),
    ("hard_hitting_news", "Hard-Hitting News"),
    ("nbn_controlling_the_message", "NBN: Controlling the Message"),
    ("crisis_management", "Crisis Management"),
    ("stock_buy_back", "Stock Buy-Back"),
    ("sandburg", "Sandburg"),
];

/// *Blood Money* (`blood_money`): tranche F5 of the FFG plan.
pub(crate) const BM_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("credit_crash", "Credit Crash"),
    ("rumor_mill", "Rumor Mill"),
    ("nfr", "Nfr"),
    ("paperclip", "Paperclip"),
    ("golden", "Golden"),
    ("temujin_contract", "Temüjin Contract"),
    ("khan_savvy_skiptracer", "Khan: Savvy Skiptracer"),
    ("data_breach", "Data Breach"),
    ("algo_trading", "Algo Trading"),
    ("beth_kilrain_chang", "Beth Kilrain-Chang"),
    ("fairchild_2_0", "Fairchild 2.0"),
    ("aiki", "Aiki"),
    ("enforcing_loyalty", "Enforcing Loyalty"),
    ("hatchet_job", "Hatchet Job"),
    ("special_report", "Special Report"),
    ("c_i_fund", "C.I. Fund"),
    ("liquidation", "Liquidation"),
    ("weyland_consortium_builder_of_nations", "Weyland Consortium: Builder of Nations"),
    ("financial_collapse", "Financial Collapse"),
    ("prisec", "Prisec"),
];

/// *Escalation* (`escalation`): tranche F5 of the FFG plan.
pub(crate) const ES_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("obelus", "Obelus"),
    ("black_orchestra", "Black Orchestra"),
    ("omar_keung_conspiracy_theorist", "Omar Keung: Conspiracy Theorist"),
    ("peregrine", "Peregrine"),
    ("houdini", "Houdini"),
    ("net_mercur", "Net Mercur"),
    ("find_the_truth", "Find the Truth"),
    ("first_responders", "First Responders"),
    ("fairchild_3_0", "Fairchild 3.0"),
    ("ark_lockdown", "Ark Lockdown"),
    ("hellion_beta_test", "Hellion Beta Test"),
    ("project_kusanagi", "Project Kusanagi"),
    ("dna_tracker", "DNA Tracker"),
    ("jinteki_potential_unleashed", "Jinteki: Potential Unleashed"),
    ("alexa_belsky", "Alexa Belsky"),
    ("observe_and_destroy", "Observe and Destroy"),
    ("service_outage", "Service Outage"),
    ("boom", "BOOM!"),
    ("door_to_door", "Door to Door"),
    ("scarcity_of_resources", "Scarcity of Resources"),
];

/// *Intervention* (`intervention`): tranche F5 of the FFG plan.
pub(crate) const IN_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("frantic_coding", "Frantic Coding"),
    ("the_gauntlet", "The Gauntlet"),
    ("saker", "Saker"),
    ("blockade_runner", "Blockade Runner"),
    ("ele_smoke_scovak_cynosure_of_the_net", "Ele \"Smoke\" Scovak: Cynosure of the Net"),
    ("top_hat", "Top Hat"),
    ("blackstone", "Blackstone"),
    ("government_investigations", "Government Investigations"),
    ("citadel_sanctuary", "Citadel Sanctuary"),
    ("wetwork_refit", "Wetwork Refit"),
    ("fumiko_yamamori", "Fumiko Yamamori"),
    ("hasty_relocation", "Hasty Relocation"),
    ("data_ward", "Data Ward"),
    ("drone_screen", "Drone Screen"),
    ("chief_slee", "Chief Slee"),
    ("bulwark", "Bulwark"),
    ("best_defense", "Best Defense"),
    ("preemptive_action", "Preemptive Action"),
];

/// *Martial Law* (`martial_law`): tranche F5 of the FFG plan.
pub(crate) const ML_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("mkultra", "MKUltra"),
    ("on_the_lam", "On the Lam"),
    ("cold_read", "Cold Read"),
    ("equivocation", "Equivocation"),
    ("misdirection", "Misdirection"),
    ("reaver", "Reaver"),
    ("interdiction", "Interdiction"),
    ("baba_yaga", "Baba Yaga"),
    ("fairchild", "Fairchild"),
    ("friends_in_high_places", "Friends in High Places"),
    ("manta_grid", "Manta Grid"),
    ("mind_game", "Mind Game"),
    ("nihongai_grid", "Nihongai Grid"),
    ("ip_block", "IP Block"),
    ("thoth", "Thoth"),
    ("anson_rose", "Anson Rose"),
    ("mausolus", "Mausolus"),
    ("sapper", "Sapper"),
    ("show_of_force", "Show of Force"),
    ("enforced_curfew", "Enforced Curfew"),
];

/// *Quorum* (`quorum`): tranche F5 of the FFG plan.
pub(crate) const QU_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("sifr", "Şifr"),
    ("sunya", "Sūnya"),
    ("recon_drone", "Recon Drone"),
    ("tapwrm", "Tapwrm"),
    ("tracker", "Tracker"),
    ("aaron_marron", "Aaron Marrón"),
    ("encore", "Encore"),
    ("fawkes", "Fawkes"),
    ("peace_in_our_time", "Peace in Our Time"),
    ("sensor_net_activation", "Sensor Net Activation"),
    ("violet_level_clearance", "Violet Level Clearance"),
    ("chiyashi", "Chiyashi"),
    ("psychokinesis", "Psychokinesis"),
    ("net_quarantine", "Net Quarantine"),
    ("herald", "Herald"),
    ("veritas", "Veritas"),
    ("bryan_stinson", "Bryan Stinson"),
    ("nasx", "NASX"),
    ("macrophage", "Macrophage"),
    ("tribunal", "Tribunal"),
];

/// *Terminal Directive Cards* (`terminal_directive_cards`): tranche F5 of the FFG
/// plan. Not in Eternal's or Snapshot's set lists, but most of its cards are
/// in both pools.
pub(crate) const TD_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("brute_force_hack", "Brute-Force-Hack"),
    ("spear_phishing", "Spear Phishing"),
    ("syn_attack", "SYN Attack"),
    ("polyhistor", "Polyhistor"),
    ("lustig", "Lustig"),
    ("demara", "Demara"),
    ("mammon", "Mammon"),
    ("charlatan", "Charlatan"),
    ("maxwell_james", "Maxwell James"),
    ("careful_planning", "Careful Planning"),
    ("deep_data_mining", "Deep Data Mining"),
    ("llds_memory_diamond", "LLDS Memory Diamond"),
    ("ubax", "Ubax"),
    ("adept", "Adept"),
    ("savant", "Savant"),
    ("dhegdheer", "Dhegdheer"),
    ("levy_advanced_research_lab", "Levy Advanced Research Lab"),
    ("laguna_velasco_district", "Laguna Velasco District"),
    ("process_automation", "Process Automation"),
    ("officer_frank", "Officer Frank"),
    ("dean_lister", "Dean Lister"),
    ("biometric_spoofing", "Biometric Spoofing"),
    ("the_shadow_net", "The Shadow Net"),
    ("seidr_laboratories_destiny_defined", "Seidr Laboratories: Destiny Defined"),
    ("brain_rewiring", "Brain Rewiring"),
    ("elective_upgrade", "Elective Upgrade"),
    ("successful_field_test", "Successful Field Test"),
    ("estelle_moon", "Estelle Moon"),
    ("eli_2_0", "Eli 2.0"),
    ("executive_functioning", "Executive Functioning"),
    ("holmegaard", "Holmegaard"),
    ("tapestry", "Tapestry"),
    ("ultraviolet_clearance", "Ultraviolet Clearance"),
    ("black_level_clearance", "Black Level Clearance"),
    ("mason_bellamy", "Mason Bellamy"),
    ("skorpios_defense_systems_persuasive_power", "Skorpios Defense Systems: Persuasive Power"),
    ("armored_servers", "Armored Servers"),
    ("illicit_sales", "Illicit Sales"),
    ("graft", "Graft"),
    ("illegal_arms_factory", "Illegal Arms Factory"),
    ("mr_stone", "Mr. Stone"),
    ("bloodletter", "Bloodletter"),
    ("hailstorm", "Hailstorm"),
    ("hunter_seeker", "Hunter Seeker"),
    ("k_p_lynn", "K. P. Lynn"),
    ("paper_trail", "Paper Trail"),
    ("honeyfarm", "Honeyfarm"),
    ("long_term_investment", "Long-Term Investment"),
    ("weir", "Weir"),
    ("ipo", "IPO"),
];

/// *Kala Ghoda* (`kala_ghoda`): tranche F6 of the FFG plan.
pub(crate) const KG_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("run_amok", "Run Amok"),
    ("ramujan_reliant_550_bmi", "Ramujan-reliant 550 BMI"),
    ("street_magic", "Street Magic"),
    ("high_stakes_job", "High-Stakes Job"),
    ("mongoose", "Mongoose"),
    ("jesminder_sareen_girl_behind_the_curtain", "Jesminder Sareen: Girl Behind the Curtain"),
    ("maya", "Maya"),
    ("panchatantra", "Panchatantra"),
    ("artist_colony", "Artist Colony"),
    ("chatterjee_university", "Chatterjee University"),
    ("advanced_concept_hopper", "Advanced Concept Hopper"),
    ("vikram_1_0", "Vikram 1.0"),
    ("heritage_committee", "Heritage Committee"),
    ("mumbad_city_grid", "Mumbad City Grid"),
    ("kala_ghoda_real_tv", "Kala Ghoda Real TV"),
    ("interrupt_0", "Interrupt 0"),
    ("dedication_ceremony", "Dedication Ceremony"),
    ("mumba_temple", "Mumba Temple"),
    ("museum_of_history", "Museum of History"),
];

/// *Business First* (`business_first`): tranche F6 of the FFG plan.
pub(crate) const BF_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("emp_device", "EMP Device"),
    ("diwan", "Diwan"),
    ("cbi_raid", "CBI Raid"),
    ("tech_trader", "Tech Trader"),
    ("netchip", "NetChip"),
    ("corporate_scandal", "Corporate Scandal"),
    ("populist_rally", "Populist Rally"),
    ("advanced_assembly_lines", "Advanced Assembly Lines"),
    ("lakshmi_smartfabrics", "Lakshmi Smartfabrics"),
    ("product_recall", "Product Recall"),
    ("palana_foods_sustainable_growth", "Pālanā Foods: Sustainable Growth"),
    ("palana_agroplex", "Pālanā Agroplex"),
    ("harvester", "Harvester"),
    ("remote_data_farm", "Remote Data Farm"),
    ("disposable_hq", "Disposable HQ"),
    ("new_construction", "New Construction"),
    ("mumbad_construction_co", "Mumbad Construction Co."),
    ("corporate_sales_team", "Corporate Sales Team"),
    ("pad_factory", "PAD Factory"),
];

/// *Democracy and Dogma* (`democracy_and_dogma`): tranche F6 of the FFG plan.
pub(crate) const DAG_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("political_graffiti", "Political Graffiti"),
    ("nero_severn_information_broker", "Nero Severn: Information Broker"),
    ("reflection", "Reflection"),
    ("spy_camera", "Spy Camera"),
    ("political_operative", "Political Operative"),
    ("sadyojata", "Sadyojata"),
    ("freedom_through_equality", "\"Freedom Through Equality\""),
    ("akshara_sareen", "Akshara Sareen"),
    ("councilman", "Councilman"),
    ("voting_machine_initiative", "Voting Machine Initiative"),
    ("clone_suffrage_movement", "Clone Suffrage Movement"),
    ("bio_ethics_association", "Bio-Ethics Association"),
    ("political_dealings", "Political Dealings"),
    ("clones_are_not_people", "\"Clones are not People\""),
    ("sensie_actors_union", "Sensie Actors Union"),
    ("commercial_bankers_group", "Commercial Bankers Group"),
    ("mumbad_city_hall", "Mumbad City Hall"),
    ("bailiff", "Bailiff"),
    ("surat_city_grid", "Surat City Grid"),
];

/// *Salsette Island* (`salsette_island`): tranche F6 of the FFG plan.
pub(crate) const SI_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("making_an_entrance", "Making an Entrance"),
    ("salsette_slums", "Salsette Slums"),
    ("exclusive_party", "Exclusive Party"),
    ("vamadeva", "Vamadeva"),
    ("brahman", "Brahman"),
    ("patron", "Patron"),
    ("sports_hopper", "Sports Hopper"),
    ("bazaar", "Bazaar"),
    ("personality_profiles", "Personality Profiles"),
    ("jeeves_model_bioroids", "Jeeves Model Bioroids"),
    ("raman_rai", "Raman Rai"),
    ("upayoga", "Upayoga"),
    ("aryabhata_tech", "Aryabhata Tech"),
    ("salems_hospitality", "Salem's Hospitality"),
    ("executive_search_firm", "Executive Search Firm"),
    ("indian_union_stock_exchange", "Indian Union Stock Exchange"),
    ("cobra", "Cobra"),
    ("localized_product_line", "Localized Product Line"),
    ("mumbad_virtual_tour", "Mumbad Virtual Tour"),
];

/// *The Liberated Mind* (`the_liberated_mind`): tranche F6 of the FFG plan.
pub(crate) const TLM_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("the_noble_path", "The Noble Path"),
    ("emptied_mind", "Emptied Mind"),
    ("information_sifting", "Information Sifting"),
    ("out_of_the_ashes", "Out of the Ashes"),
    ("liberated_chela", "Liberated Chela"),
    ("temple_of_the_liberated_mind", "Temple of the Liberated Mind"),
    ("rebirth", "Rebirth"),
    ("guru_davinder", "Guru Davinder"),
    ("the_turning_wheel", "The Turning Wheel"),
    ("brainstorm", "Brainstorm"),
    ("dedicated_neural_net", "Dedicated Neural Net"),
    ("chetana", "Chetana"),
    ("puppet_master", "Puppet Master"),
    ("waiver", "Waiver"),
    ("exchange_of_information", "Exchange of Information"),
    ("red_tape", "Red Tape"),
    ("consulting_visit", "Consulting Visit"),
    ("vanilla", "Vanilla"),
];

/// *Fear the Masses* (`fear_the_masses`): tranche F6 of the FFG plan.
pub(crate) const FTM_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("fear_the_masses", "Fear the Masses"),
    ("aghora", "Aghora"),
    ("bhagat", "Bhagat"),
    ("the_black_file", "The Black File"),
    ("the_price_of_freedom", "The Price of Freedom"),
    ("ankusa", "Ankusa"),
    ("rigged_results", "Rigged Results"),
    ("lateral_growth", "Lateral Growth"),
    ("improved_protein_source", "Improved Protein Source"),
    ("voter_intimidation", "Voter Intimidation"),
    ("harishchandra_ent_where_youre_the_star", "Harishchandra Ent.: Where You're the Star"),
    ("full_immersion_recstudio", "Full Immersion RecStudio"),
    ("ibrahim_salem", "Ibrahim Salem"),
    ("navi_mumbai_city_grid", "Navi Mumbai City Grid"),
    ("zealous_judge", "Zealous Judge"),
    ("election_day", "Election Day"),
    ("subcontract", "Subcontract"),
    ("merger", "Merger"),
];

/// *Data and Destiny* (`data_and_destiny`): tranche F6 of the FFG plan.
pub(crate) const DAD_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("sync_everything_everywhere", "SYNC: Everything, Everywhere"),
    ("new_angeles_sol_your_news", "New Angeles Sol: Your News"),
    ("spark_agency_worldswide_reach", "Spark Agency: Worldswide Reach"),
    ("15_minutes", "15 Minutes"),
    ("improved_tracers", "Improved Tracers"),
    ("rebranding_team", "Rebranding Team"),
    ("quantum_predictive_model", "Quantum Predictive Model"),
    ("lily_lockwell", "Lily Lockwell"),
    ("news_team", "News Team"),
    ("shannon_claire", "Shannon Claire"),
    ("victoria_jenkins", "Victoria Jenkins"),
    ("reality_threedee", "Reality Threedee"),
    ("archangel", "Archangel"),
    ("news_hound", "News Hound"),
    ("resistor", "Resistor"),
    ("special_offer", "Special Offer"),
    ("tl_dr", "TL;DR"),
    ("turnpike", "Turnpike"),
    ("24_7_news_cycle", "24/7 News Cycle"),
    ("ad_blitz", "Ad Blitz"),
    ("media_blitz", "Media Blitz"),
    ("the_all_seeing_i", "The All-Seeing I"),
    ("surveillance_sweep", "Surveillance Sweep"),
    ("keegan_lane", "Keegan Lane"),
    ("rutherford_grid", "Rutherford Grid"),
    ("global_food_initiative", "Global Food Initiative"),
    ("launch_campaign", "Launch Campaign"),
    ("assassin", "Assassin"),
    ("apex_invasive_predator", "Apex: Invasive Predator"),
    ("apocalypse", "Apocalypse"),
    ("prey", "Prey"),
    ("heartbeat", "Heartbeat"),
    ("endless_hunger", "Endless Hunger"),
    ("harbinger", "Harbinger"),
    ("hunting_grounds", "Hunting Grounds"),
    ("wasteland", "Wasteland"),
    ("adam_compulsive_hacker", "Adam: Compulsive Hacker"),
    ("independent_thinking", "Independent Thinking"),
    ("brain_chip", "Brain Chip"),
    ("multithreader", "Multithreader"),
    ("always_be_running", "Always Be Running"),
    ("dr_lovegood", "Dr. Lovegood"),
    ("neutralize_all_threats", "Neutralize All Threats"),
    ("safety_first", "Safety First"),
    ("sunny_lebeau_security_specialist", "Sunny Lebeau: Security Specialist"),
    ("security_chip", "Security Chip"),
    ("security_nexus", "Security Nexus"),
    ("gs_striker_m1", "GS Striker M1"),
    ("gs_shrike_m2", "GS Shrike M2"),
    ("gs_sherman_m3", "GS Sherman M3"),
    ("globalsec_security_clearance", "Globalsec Security Clearance"),
    ("jak_sinclair", "Jak Sinclair"),
    ("employee_strike", "Employee Strike"),
    ("windfall", "Windfall"),
    ("technical_writer", "Technical Writer"),
];

/// *The Valley* (`the_valley`): tranche F7 of the FFG plan.
pub(crate) const VAL_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("paige_piper", "Paige Piper"),
    ("adjusted_chronotype", "Adjusted Chronotype"),
    ("spike", "Spike"),
    ("enhanced_vision", "Enhanced Vision"),
    ("gene_conditioning_shoppe", "Gene Conditioning Shoppe"),
    ("synthetic_blood", "Synthetic Blood"),
    ("traffic_jam", "Traffic Jam"),
    ("symmetrical_visage", "Symmetrical Visage"),
    ("brain_taping_warehouse", "Brain-Taping Warehouse"),
    ("next_gold", "NEXT Gold"),
    ("jinteki_biotech_life_imagined", "Jinteki Biotech: Life Imagined"),
    ("genetic_resequencing", "Genetic Resequencing"),
    ("cortex_lock", "Cortex Lock"),
    ("valley_grid", "Valley Grid"),
    ("bandwidth", "Bandwidth"),
    ("predictive_algorithm", "Predictive Algorithm"),
    ("capital_investors", "Capital Investors"),
    ("negotiator", "Negotiator"),
    ("tech_startup", "Tech Startup"),
];

/// *Breaker Bay* (`breaker_bay`): tranche F7 of the FFG plan.
pub(crate) const BB_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("hacktivist_meeting", "Hacktivist Meeting"),
    ("off_campus_apartment", "Off-Campus Apartment"),
    ("dorm_computer", "Dorm Computer"),
    ("hayley_kaplan_universal_scholar", "Hayley Kaplan: Universal Scholar"),
    ("game_day", "Game Day"),
    ("comet", "Comet"),
    ("study_guide", "Study Guide"),
    ("london_library", "London Library"),
    ("tyson_observatory", "Tyson Observatory"),
    ("beach_party", "Beach Party"),
    ("research_grant", "Research Grant"),
    ("turing", "Turing"),
    ("crick", "Crick"),
    ("recruiting_trip", "Recruiting Trip"),
    ("blacklist", "Blacklist"),
    ("gutenberg", "Gutenberg"),
    ("student_loans", "Student Loans"),
    ("meru_mati", "Meru Mati"),
    ("breaker_bay_grid", "Breaker Bay Grid"),
];

/// *Chrome City* (`chrome_city`): tranche F7 of the FFG plan.
pub(crate) const CC_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("immolation_script", "Immolation Script"),
    ("skulljack", "Skulljack"),
    ("turntable", "Turntable"),
    ("chrome_parlor", "Chrome Parlor"),
    ("titanium_ribs", "Titanium Ribs"),
    ("crowbar", "Crowbar"),
    ("net_ready_eyes", "Net-Ready Eyes"),
    ("analog_dreamers", "Analog Dreamers"),
    ("brain_cage", "Brain Cage"),
    ("cybernetics_division_humanity_upgraded", "Cybernetics Division: Humanity Upgraded"),
    ("self_destruct_chips", "Self-Destruct Chips"),
    ("lab_dog", "Lab Dog"),
    ("oaktown_grid", "Oaktown Grid"),
    ("ryon_knight", "Ryon Knight"),
    ("clairvoyant_monitor", "Clairvoyant Monitor"),
    ("lockdown", "Lockdown"),
    ("little_engine", "Little Engine"),
    ("quicksand", "Quicksand"),
];

/// *The Underway* (`the_underway`): tranche F7 of the FFG plan.
pub(crate) const UW_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("faust", "Faust"),
    ("street_peddler", "Street Peddler"),
    ("armand_geist_walker_tech_lord", "Armand \"Geist\" Walker: Tech Lord"),
    ("drive_by", "Drive By"),
    ("forger", "Forger"),
    ("shiv", "Shiv"),
    ("gang_sign", "Gang Sign"),
    ("muertos_gang_member", "Muertos Gang Member"),
    ("hyperdriver", "Hyperdriver"),
    ("test_ground", "Test Ground"),
    ("defective_brainchips", "Defective Brainchips"),
    ("allele_repression", "Allele Repression"),
    ("marcus_batty", "Marcus Batty"),
    ("expose", "Exposé"),
    ("pachinko", "Pachinko"),
    ("underway_renovation", "Underway Renovation"),
    ("contract_killer", "Contract Killer"),
    ("spiderweb", "Spiderweb"),
    ("underway_grid", "Underway Grid"),
];

/// *Old Hollywood* (`old_hollywood`): tranche F7 of the FFG plan.
pub(crate) const OH_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("trope", "Trope"),
    ("spoilers", "Spoilers"),
    ("drug_dealer", "Drug Dealer"),
    ("rolodex", "Rolodex"),
    ("fan_site", "Fan Site"),
    ("film_critic", "Film Critic"),
    ("paparazzi", "Paparazzi"),
    ("ronald_five", "Ronald Five"),
    ("enforcer_1_0", "Enforcer 1.0"),
    ("its_a_trap", "It's a Trap!"),
    ("an_offer_you_cant_refuse", "An Offer You Can’t Refuse"),
    ("haarpsichord_studios_entertainment_unleashed", "Haarpsichord Studios: Entertainment Unleashed"),
    ("award_bait", "Award Bait"),
    ("explode_a_palooza", "Explode-a-palooza"),
    ("early_premiere", "Early Premiere"),
    ("casting_call", "Casting Call"),
    ("old_hollywood_grid", "Old Hollywood Grid"),
    ("hollywood_renovation", "Hollywood Renovation"),
    ("back_channels", "Back Channels"),
    ("vanity_project", "Vanity Project"),
];

/// *The Universe of Tomorrow* (`the_universe_of_tomorrow`): tranche F7 of the FFG plan.
pub(crate) const UOT_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("power_to_the_people", "Power to the People"),
    ("surfer", "Surfer"),
    ("ddos", "DDoS"),
    ("laramy_fisk_savvy_investor", "Laramy Fisk: Savvy Investor"),
    ("fisk_investment_seminar", "Fisk Investment Seminar"),
    ("bookmark", "Bookmark"),
    ("davinci", "DaVinci"),
    ("wireless_net_pavilion", "Wireless Net Pavilion"),
    ("cybernetics_court", "Cybernetics Court"),
    ("team_sponsorship", "Team Sponsorship"),
    ("chronos_protocol_selective_mind_mapping", "Chronos Protocol: Selective Mind-mapping"),
    ("ancestral_imager", "Ancestral Imager"),
    ("genetics_pavilion", "Genetics Pavilion"),
    ("franchise_city", "Franchise City"),
    ("product_placement", "Product Placement"),
    ("worlds_plaza", "Worlds Plaza"),
    ("public_support", "Public Support"),
    ("tour_guide", "Tour Guide"),
    ("expo_grid", "Expo Grid"),
    ("the_future_is_now", "The Future is Now"),
];

/// *Order and Chaos* (`order_and_chaos`): tranche F7 of the FFG plan.
pub(crate) const OAC_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("argus_security_protection_guaranteed", "Argus Security: Protection Guaranteed"),
    ("gagarin_deep_space_expanding_the_horizon", "Gagarin Deep Space: Expanding the Horizon"),
    ("titan_transnational_investing_in_your_future", "Titan Transnational: Investing In Your Future"),
    ("firmware_updates", "Firmware Updates"),
    ("glenn_station", "Glenn Station"),
    ("government_takeover", "Government Takeover"),
    ("high_risk_investment", "High-Risk Investment"),
    ("constellation_protocol", "Constellation Protocol"),
    ("mark_yale", "Mark Yale"),
    ("space_camp", "Space Camp"),
    ("the_board", "The Board"),
    ("asteroid_belt", "Asteroid Belt"),
    ("wormhole", "Wormhole"),
    ("nebula", "Nebula"),
    ("orion", "Orion"),
    ("builder", "Builder"),
    ("checkpoint", "Checkpoint"),
    ("fire_wall", "Fire Wall"),
    ("searchlight", "Searchlight"),
    ("housekeeping", "Housekeeping"),
    ("patch", "Patch"),
    ("traffic_accident", "Traffic Accident"),
    ("satellite_grid", "Satellite Grid"),
    ("the_twins", "The Twins"),
    ("sub_boost", "Sub Boost"),
    ("dedicated_technician_team", "Dedicated Technician Team"),
    ("cyberdex_virus_suite", "Cyberdex Virus Suite"),
    ("edward_kim_humanitys_hammer", "Edward Kim: Humanity's Hammer"),
    ("maxx_maximum_punk_rock", "MaxX: Maximum Punk Rock"),
    ("valencia_estevez_the_angel_of_cayambe", "Valencia Estevez: The Angel of Cayambe"),
    ("amped_up", "Amped Up"),
    ("ive_had_worse", "I've Had Worse"),
    ("itinerant_protesters", "Itinerant Protesters"),
    ("showing_off", "Showing Off"),
    ("wanton_destruction", "Wanton Destruction"),
    ("day_job", "Day Job"),
    ("forked", "Forked"),
    ("knifed", "Knifed"),
    ("spooned", "Spooned"),
    ("eater", "Eater"),
    ("gravedigger", "Gravedigger"),
    ("hivemind", "Hivemind"),
    ("progenitor", "Progenitor"),
    ("archives_interface", "Archives Interface"),
    ("chop_bot_3000", "Chop Bot 3000"),
    ("memstrips", "MemStrips"),
    ("vigil", "Vigil"),
    ("human_first", "Human First"),
    ("investigative_journalism", "Investigative Journalism"),
    ("sacrificial_clone", "Sacrificial Clone"),
    ("stim_dealer", "Stim Dealer"),
    ("virus_breeding_ground", "Virus Breeding Ground"),
    ("uninstall", "Uninstall"),
    ("qianju_pt", "Qianju PT"),
    ("data_folding", "Data Folding"),
];

/// *Upstalk* (`upstalk`): tranche F8 of the FFG plan.
pub(crate) const UP_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("domestic_sleepers", "Domestic Sleepers"),
    ("mutate", "Mutate"),
    ("primary_transmission_dish", "Primary Transmission Dish"),
    ("midway_station_grid", "Midway Station Grid"),
    ("the_root", "The Root"),
    ("taurus", "Taurus"),
    ("mother_goddess", "Mother Goddess"),
    ("galahad", "Galahad"),
    ("bad_times", "Bad Times"),
    ("cyber_threat", "Cyber Threat"),
    ("lamprey", "Lamprey"),
    ("paper_tripping", "Paper Tripping"),
    ("power_tap", "Power Tap"),
    ("nasir_meidan_cyber_explorer", "Nasir Meidan: Cyber Explorer"),
    ("social_engineering", "Social Engineering"),
    ("leprechaun", "Leprechaun"),
    ("eden_shard", "Eden Shard"),
];

/// *The Spaces Between* (`the_spaces_between`): tranche F8 of the FFG plan.
pub(crate) const TSB_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("the_foundry_refining_the_process", "The Foundry: Refining the Process"),
    ("enhanced_login_protocol", "Enhanced Login Protocol"),
    ("heinlein_grid", "Heinlein Grid"),
    ("encrypted_portals", "Encrypted Portals"),
    ("cerebral_static", "Cerebral Static"),
    ("targeted_marketing", "Targeted Marketing"),
    ("information_overload", "Information Overload"),
    ("paywall_implementation", "Paywall Implementation"),
    ("sealed_vault", "Sealed Vault"),
    ("eden_fragment", "Eden Fragment"),
    ("lag_time", "Lag Time"),
    ("will_o_the_wisp", "Will-o'-the-Wisp"),
    ("d4v1d", "D4v1d"),
    ("scrubbed", "Scrubbed"),
    ("three_steps_ahead", "Three Steps Ahead"),
    ("unscheduled_maintenance", "Unscheduled Maintenance"),
    ("net_celebrity", "Net Celebrity"),
    ("llds_energy_regulator", "LLDS Energy Regulator"),
    ("ghost_runner", "Ghost Runner"),
];

/// *First Contact* (`first_contact`): tranche F8 of the FFG plan.
pub(crate) const FC_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("iq", "IQ"),
    ("elizas_toybox", "Eliza's Toybox"),
    ("kitsune", "Kitsune"),
    ("port_anson_grid", "Port Anson Grid"),
    ("the_news_now_hour", "The News Now Hour"),
    ("manhunt", "Manhunt"),
    ("wendigo", "Wendigo"),
    ("chronos_project", "Chronos Project"),
    ("shattered_remains", "Shattered Remains"),
    ("lancelot", "Lancelot"),
    ("blackat", "BlacKat"),
    ("duggars", "Duggar's"),
    ("box_e", "Box-E"),
    ("the_supplier", "The Supplier"),
    ("refractor", "Refractor"),
    ("order_of_sol", "Order of Sol"),
    ("hades_shard", "Hades Shard"),
    ("rachel_beckman", "Rachel Beckman"),
];

/// *Up and Over* (`up_and_over`): tranche F8 of the FFG plan.
pub(crate) const UAO_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("architect", "Architect"),
    ("peak_efficiency", "Peak Efficiency"),
    ("labyrinthine_servers", "Labyrinthine Servers"),
    ("ashigaru", "Ashigaru"),
    ("mamba", "Mamba"),
    ("universal_connectivity_fee", "Universal Connectivity Fee"),
    ("blue_sun_powering_the_future", "Blue Sun: Powering the Future"),
    ("changeling", "Changeling"),
    ("reuse", "Reuse"),
    ("hades_fragment", "Hades Fragment"),
    ("docklands_crackdown", "Docklands Crackdown"),
    ("inject", "Inject"),
    ("origami", "Origami"),
    ("fester", "Fester"),
    ("autoscripter", "Autoscripter"),
    ("switchblade", "Switchblade"),
    ("trade_in", "Trade-In"),
    ("astrolabe", "Astrolabe"),
    ("angel_arena", "Angel Arena"),
];

/// *All That Remains* (`all_that_remains`): tranche F8 of the FFG plan.
pub(crate) const ATR_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("bifrost_array", "Bifrost Array"),
    ("sagittarius", "Sagittarius"),
    ("gemini", "Gemini"),
    ("superior_cyberwalls", "Superior Cyberwalls"),
    ("lycan", "Lycan"),
    ("snatch_and_grab", "Snatch and Grab"),
    ("merlin", "Merlin"),
    ("shell_corporation", "Shell Corporation"),
    ("ekomind", "Ekomind"),
    ("cerberus_cuj_0_h3", "Cerberus \"Cuj.0\" H3"),
    ("leela_patel_trained_pragmatist", "Leela Patel: Trained Pragmatist"),
    ("cerberus_rex_h2", "Cerberus \"Rex\" H2"),
    ("zona_sul_shipping", "Zona Sul Shipping"),
    ("cybsoft_macrodrive", "Cybsoft MacroDrive"),
    ("utopia_shard", "Utopia Shard"),
];

/// *The Source* (`the_source`): tranche F8 of the FFG plan.
pub(crate) const TS_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("helium_3_deposit", "Helium-3 Deposit"),
    ("errand_boy", "Errand Boy"),
    ("it_department", "IT Department"),
    ("markus_1_0", "Markus 1.0"),
    ("industrial_genomics_growing_solutions", "Industrial Genomics: Growing Solutions"),
    ("shoot_the_moon", "Shoot the Moon"),
    ("troll", "Troll"),
    ("virgo", "Virgo"),
    ("utopia_fragment", "Utopia Fragment"),
    ("self_destruct", "Self-destruct"),
    ("incubator", "Incubator"),
    ("ixodidae", "Ixodidae"),
    ("code_siphon", "Code Siphon"),
    ("collective_consciousness", "Collective Consciousness"),
    ("sage", "Sage"),
    ("bribery", "Bribery"),
    ("au_revoir", "Au Revoir"),
];

/// *Honor and Profit* (`honor_and_profit`): tranche F8 of the FFG plan.
pub(crate) const HAP_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("harmony_medtech_biomedical_pioneer", "Harmony Medtech: Biomedical Pioneer"),
    ("nisei_division_the_next_generation", "Nisei Division: The Next Generation"),
    ("tennin_institute_the_secrets_within", "Tennin Institute: The Secrets Within"),
    ("medical_breakthrough", "Medical Breakthrough"),
    ("philotic_entanglement", "Philotic Entanglement"),
    ("the_future_perfect", "The Future Perfect"),
    ("chairman_hiro", "Chairman Hiro"),
    ("mental_health_clinic", "Mental Health Clinic"),
    ("psychic_field", "Psychic Field"),
    ("shi_kyu", "Shi.Kyū"),
    ("tenma_line", "Tenma Line"),
    ("cerebral_cast", "Cerebral Cast"),
    ("medical_research_fundraiser", "Medical Research Fundraiser"),
    ("mushin_no_shin", "Mushin No Shin"),
    ("inazuma", "Inazuma"),
    ("komainu", "Komainu"),
    ("pup", "Pup"),
    ("shiro", "Shiro"),
    ("susanoo_no_mikoto", "Susanoo-no-Mikoto"),
    ("neotokyo_grid", "NeoTokyo Grid"),
    ("tori_hanzo", "Tori Hanzō"),
    ("plan_b", "Plan B"),
    ("guard", "Guard"),
    ("rainbow", "Rainbow"),
    ("diversified_portfolio", "Diversified Portfolio"),
    ("fast_track", "Fast Track"),
    ("iain_stirling_retired_spook", "Iain Stirling: Retired Spook"),
    ("silhouette_stealth_operative", "Silhouette: Stealth Operative"),
    ("calling_in_favors", "Calling in Favors"),
    ("early_bird", "Early Bird"),
    ("express_delivery", "Express Delivery"),
    ("feint", "Feint"),
    ("planned_assault", "Planned Assault"),
    ("logos", "Logos"),
    ("public_terminal", "Public Terminal"),
    ("unregistered_s_w_35", "Unregistered S&W '35"),
    ("window", "Window"),
    ("alias", "Alias"),
    ("breach", "Breach"),
    ("bug", "Bug"),
    ("gingerbread", "Gingerbread"),
    ("grappling_hook", "Grappling Hook"),
    ("passport", "Passport"),
    ("push_your_luck", "Push Your Luck"),
    ("theophilius_bagbiter", "Theophilius Bagbiter"),
    ("tri_maf_contact", "Tri-maf Contact"),
    ("mass_install", "Mass Install"),
    ("q_coherence_chip", "Q-Coherence Chip"),
    ("overmind", "Overmind"),
    ("oracle_may", "Oracle May"),
    ("donut_taganes", "Donut Taganes"),
];

/// *Creation and Control* (`creation_and_control`): tranche F9 of the FFG plan.
pub(crate) const CAC_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("cerebral_imaging_infinite_frontiers", "Cerebral Imaging: Infinite Frontiers"),
    ("custom_biotics_engineered_for_success", "Custom Biotics: Engineered for Success"),
    ("next_design_guarding_the_net", "NEXT Design: Guarding the Net"),
    ("director_haas_pet_project", "Director Haas' Pet Project"),
    ("efficiency_committee", "Efficiency Committee"),
    ("project_wotan", "Project Wotan"),
    ("sentinel_defense_program", "Sentinel Defense Program"),
    ("alix_t4lb07", "Alix T4LB07"),
    ("director_haas", "Director Haas"),
    ("haas_arcology_ai", "Haas Arcology AI"),
    ("thomas_haas", "Thomas Haas"),
    ("bioroid_efficiency_research", "Bioroid Efficiency Research"),
    ("successful_demonstration", "Successful Demonstration"),
    ("heimdall_2_0", "Heimdall 2.0"),
    ("howler", "Howler"),
    ("ichi_2_0", "Ichi 2.0"),
    ("minelayer", "Minelayer"),
    ("viktor_2_0", "Viktor 2.0"),
    ("zed_1_0", "Zed 1.0"),
    ("awakening_center", "Awakening Center"),
    ("tyrs_hand", "Tyr's Hand"),
    ("gila_hands_arcology", "Gila Hands Arcology"),
    ("levy_university", "Levy University"),
    ("server_diagnostics", "Server Diagnostics"),
    ("bastion", "Bastion"),
    ("datapike", "Datapike"),
    ("the_professor_keeper_of_knowledge", "The Professor: Keeper of Knowledge"),
    ("exile_streethawk", "Exile: Streethawk"),
    ("escher", "Escher"),
    ("exploratory_romp", "Exploratory Romp"),
    ("freelance_coding_contract", "Freelance Coding Contract"),
    ("scavenge", "Scavenge"),
    ("levy_ar_lab_access", "Levy AR Lab Access"),
    ("monolith", "Monolith"),
    ("feedback_filter", "Feedback Filter"),
    ("clone_chip", "Clone Chip"),
    ("omni_drive", "Omni-drive"),
    ("cloak", "Cloak"),
    ("dagger", "Dagger"),
    ("chakana", "Chakana"),
    ("cyber_cypher", "Cyber-Cypher"),
    ("sahasrara", "Sahasrara"),
    ("inti", "Inti"),
    ("borrowed_satellite", "Borrowed Satellite"),
    ("ice_analyzer", "Ice Analyzer"),
    ("same_old_thing", "Same Old Thing"),
    ("the_source", "The Source"),
];

/// *Opening Moves* (`opening_moves`): tranche F10 of the FFG plan.
pub(crate) const OM_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("frame_job", "Frame Job"),
    ("pawn", "Pawn"),
    ("rook", "Rook"),
    ("hostage", "Hostage"),
    ("gorman_drip_v1", "Gorman Drip v1"),
    ("lockpick", "Lockpick"),
    ("false_echo", "False Echo"),
    ("motivation", "Motivation"),
    ("john_masanori", "John Masanori"),
    ("project_ares", "Project Ares"),
    ("himitsu_bako", "Himitsu-Bako"),
    ("character_assassination", "Character Assassination"),
    ("jackson_howard", "Jackson Howard"),
    ("invasion_of_privacy", "Invasion of Privacy"),
    ("geothermal_fracking", "Geothermal Fracking"),
    ("swarm", "Swarm"),
    ("cyberdex_trial", "Cyberdex Trial"),
    ("grim", "Grim"),
];

/// *Second Thoughts* (`second_thoughts`): tranche F10 of the FFG plan.
pub(crate) const ST_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("bishop", "Bishop"),
    ("scheherazade", "Scheherazade"),
    ("hard_at_work", "Hard at Work"),
    ("recon", "Recon"),
    ("copycat", "Copycat"),
    ("leviathan", "Leviathan"),
    ("eureka", "Eureka!"),
    ("record_reconstructor", "Record Reconstructor"),
    ("wotan", "Wotan"),
    ("hellion_alpha_test", "Hellion Alpha Test"),
    ("clone_retirement", "Clone Retirement"),
    ("shipment_from_sansan", "Shipment from SanSan"),
    ("muckraker", "Muckraker"),
    ("the_cleaners", "The Cleaners"),
    ("elizabeth_mills", "Elizabeth Mills"),
    ("off_the_grid", "Off the Grid"),
    ("profiteering", "Profiteering"),
    ("restructure", "Restructure"),
];

/// *Mala Tempora* (`mala_tempora`): tranche F10 of the FFG plan.
pub(crate) const MT_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("deep_red", "Deep Red"),
    ("knight", "Knight"),
    ("running_interference", "Running Interference"),
    ("expert_schedule_analyzer", "Expert Schedule Analyzer"),
    ("grifter", "Grifter"),
    ("torch", "Torch"),
    ("woman_in_the_red_dress", "Woman in the Red Dress"),
    ("raymond_flint", "Raymond Flint"),
    ("isabel_mcguire", "Isabel McGuire"),
    ("hudson_1_0", "Hudson 1.0"),
    ("accelerated_diagnostics", "Accelerated Diagnostics"),
    ("unorthodox_predictions", "Unorthodox Predictions"),
    ("sundew", "Sundew"),
    ("city_surveillance", "City Surveillance"),
    ("snoop", "Snoop"),
    ("ireress", "Ireress"),
    ("power_shutdown", "Power Shutdown"),
    ("paper_wall", "Paper Wall"),
    ("interns", "Interns"),
];

/// *True Colors* (`true_colors`): tranche F10 of the FFG plan.
pub(crate) const TC_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("keyhole", "Keyhole"),
    ("activist_support", "Activist Support"),
    ("lawyer_up", "Lawyer Up"),
    ("leverage", "Leverage"),
    ("garrote", "Garrote"),
    ("llds_processor", "LLDS Processor"),
    ("sharpshooter", "Sharpshooter"),
    ("capstone", "Capstone"),
    ("starlight_crusade_funding", "Starlight Crusade Funding"),
    ("rex_campaign", "Rex Campaign"),
    ("fenris", "Fenris"),
    ("panic_button", "Panic Button"),
    ("shock", "Shock!"),
    ("tsurugi", "Tsurugi"),
    ("tgtbt", "TGTBT"),
    ("rsvp", "RSVP"),
    ("curtain_wall", "Curtain Wall"),
    ("veterans_program", "Veterans Program"),
];

/// *Fear and Loathing* (`fear_and_loathing`): tranche F10 of the FFG plan.
pub(crate) const FAL_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("quest_completed", "Quest Completed"),
    ("hemorrhage", "Hemorrhage"),
    ("tallie_perrault", "Tallie Perrault"),
    ("executive_wiretaps", "Executive Wiretaps"),
    ("blackguard", "Blackguard"),
    ("cybersolutions_mem_chip", "CyberSolutions Mem Chip"),
    ("alpha", "Alpha"),
    ("omega", "Omega"),
    ("blackmail", "Blackmail"),
    ("blue_level_clearance", "Blue Level Clearance"),
    ("strongbox", "Strongbox"),
    ("toshiyuki_sakai", "Toshiyuki Sakai"),
    ("yagura", "Yagura"),
    ("restoring_face", "Restoring Face"),
    ("market_research", "Market Research"),
    ("grndl_power_unleashed", "GRNDL: Power Unleashed"),
    ("vulcan_coverup", "Vulcan Coverup"),
    ("grndl_refinery", "GRNDL Refinery"),
];

/// *Double Time* (`double_time`): tranche F10 of the FFG plan.
pub(crate) const DT_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("singularity", "Singularity"),
    ("queens_gambit", "Queen's Gambit"),
    ("dyson_fractal_generator", "Dyson Fractal Generator"),
    ("silencer", "Silencer"),
    ("savoir_faire", "Savoir-faire"),
    ("fall_guy", "Fall Guy"),
    ("power_nap", "Power Nap"),
    ("paintbrush", "Paintbrush"),
    ("gyri_labyrinth", "Gyri Labyrinth"),
    ("reclamation_order", "Reclamation Order"),
    ("broadcast_square", "Broadcast Square"),
    ("corporate_shuffle", "Corporate Shuffle"),
    ("caprice_nisei", "Caprice Nisei"),
    ("shinobi", "Shinobi"),
    ("marker", "Marker"),
    ("hive", "Hive"),
    ("witness_tampering", "Witness Tampering"),
    ("napd_contract", "NAPD Contract"),
    ("quandary", "Quandary"),
];

/// *What Lies Ahead* (`what_lies_ahead`): tranche F11 of the FFG plan.
pub(crate) const WLA_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("whizzard_master_gamer", "Whizzard: Master Gamer"),
    ("spinal_modem", "Spinal Modem"),
    ("morning_star", "Morning Star"),
    ("cortez_chip", "Cortez Chip"),
    ("peacock", "Peacock"),
    ("zu_13_key_master", "ZU.13 Key Master"),
    ("the_helpful_ai", "The Helpful AI"),
    ("plascrete_carapace", "Plascrete Carapace"),
    ("haas_bioroid_stronger_together", "Haas-Bioroid: Stronger Together"),
    ("mandatory_upgrades", "Mandatory Upgrades"),
    ("janus_1_0", "Janus 1.0"),
    ("ash_2x3zb9cy", "Ash 2X3ZB9CY"),
    ("braintrust", "Braintrust"),
    ("snowflake", "Snowflake"),
    ("restructured_datapool", "Restructured Datapool"),
    ("tmi", "TMI"),
    ("caduceus", "Caduceus"),
    ("draco", "Dracō"),
];

/// *Trace Amount* (`trace_amount`): tranche F11 of the FFG plan.
pub(crate) const TA_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("vamp", "Vamp"),
    ("satellite_uplink", "Satellite Uplink"),
    ("compromised_employee", "Compromised Employee"),
    ("notoriety", "Notoriety"),
    ("snowball", "Snowball"),
    ("dyson_mem_chip", "Dyson Mem Chip"),
    ("encryption_protocol", "Encryption Protocol"),
    ("sherlock_1_0", "Sherlock 1.0"),
    ("jinteki_replicating_perfection", "Jinteki: Replicating Perfection"),
    ("fetal_ai", "Fetal AI"),
    ("sensei", "Sensei"),
    ("big_brother", "Big Brother"),
    ("chilo_city_grid", "ChiLo City Grid"),
    ("power_grid_overload", "Power Grid Overload"),
    ("amazon_industrial_zone", "Amazon Industrial Zone"),
    ("executive_retreat", "Executive Retreat"),
    ("freelancer", "Freelancer"),
];

/// *Cyber Exodus* (`cyber_exodus`): tranche F11 of the FFG plan.
pub(crate) const CE_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("nerve_agent", "Nerve Agent"),
    ("joshua_b", "Joshua B."),
    ("muresh_bodysuit", "Muresh Bodysuit"),
    ("snitch", "Snitch"),
    ("chaos_theory_wunderkind", "Chaos Theory: Wünderkind"),
    ("dinosaurus", "Dinosaurus"),
    ("personal_workshop", "Personal Workshop"),
    ("public_sympathy", "Public Sympathy"),
    ("viper", "Viper"),
    ("edge_of_world", "Edge of World"),
    ("sunset", "Sunset"),
    ("marked_accounts", "Marked Accounts"),
    ("woodcutter", "Woodcutter"),
    ("commercialization", "Commercialization"),
    ("private_contracts", "Private Contracts"),
    ("chimera", "Chimera"),
];

/// *A Study in Static* (`a_study_in_static`): tranche F11 of the FFG plan.
pub(crate) const ASIS_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("disrupter", "Disrupter"),
    ("force_of_nature", "Force of Nature"),
    ("doppelganger", "Doppelgänger"),
    ("crescentus", "Crescentus"),
    ("deus_x", "Deus X"),
    ("all_nighter", "All-nighter"),
    ("inside_man", "Inside Man"),
    ("underworld_contact", "Underworld Contact"),
    ("green_level_clearance", "Green Level Clearance"),
    ("hourglass", "Hourglass"),
    ("dedicated_server", "Dedicated Server"),
    ("bullfrog", "Bullfrog"),
    ("uroboros", "Uroboros"),
    ("net_police", "Net Police"),
    ("weyland_consortium_because_we_built_it", "Weyland Consortium: Because We Built It"),
    ("government_contracts", "Government Contracts"),
    ("tyrant", "Tyrant"),
    ("oversight_ai", "Oversight AI"),
];

/// *Humanity's Shadow* (`humanitys_shadow`): tranche F11 of the FFG plan.
pub(crate) const HS_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("surge", "Surge"),
    ("andromeda_dispossessed_ristie", "Andromeda: Dispossessed Ristie"),
    ("hq_interface", "HQ Interface"),
    ("pheromones", "Pheromones"),
    ("quality_time", "Quality Time"),
    ("replicator", "Replicator"),
    ("creeper", "Creeper"),
    ("kraken", "Kraken"),
    ("kati_jones", "Kati Jones"),
    ("eve_campaign", "Eve Campaign"),
    ("rework", "Rework"),
    ("whirlpool", "Whirlpool"),
    ("data_hound", "Data Hound"),
    ("bernice_mai", "Bernice Mai"),
    ("salvage", "Salvage"),
    ("simone_diego", "Simone Diego"),
    ("foxfire", "Foxfire"),
];

/// *Future Proof* (`future_proof`): tranche F11 of the FFG plan.
pub(crate) const FP_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("darwin", "Darwin"),
    ("data_leak_reversal", "Data Leak Reversal"),
    ("faerie", "Faerie"),
    ("mr_li", "Mr. Li"),
    ("r_d_interface", "R&D Interface"),
    ("deep_thought", "Deep Thought"),
    ("new_angeles_city_hall", "New Angeles City Hall"),
    ("ruhr_valley", "Ruhr Valley"),
    ("midori", "Midori"),
    ("nbn_the_world_is_yours", "NBN: The World is Yours*"),
    ("midseason_replacements", "Midseason Replacements"),
    ("flare", "Flare"),
    ("dedicated_response_team", "Dedicated Response Team"),
    ("burke_bugs", "Burke Bugs"),
    ("corporate_war", "Corporate War"),
];

/// *NAPD Multiplayer* (`napd_multiplayer`): tranche F12 of the FFG plan.
pub(crate) const NAPD_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("cyber_bureau_keeping_the_peace", "Cyber Bureau: Keeping the Peace"),
];

/// *Magnum Opus* (`magnum_opus`): tranche F12 of the FFG plan.
pub(crate) const MO_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("watch_the_world_burn", "Watch the World Burn"),
    ("hired_help", "Hired Help"),
];

/// *System Core 2019* (`system_core_2019`): tranche F12 of the FFG plan.
pub(crate) const SC19_UNIMPLEMENTED: &[(&str, &str)] = &[
    ("queens_gambit", "Queen's Gambit"),
    ("quest_completed", "Quest Completed"),
    ("run_amok", "Run Amok"),
    ("patchwork", "Patchwork"),
    ("force_of_nature", "Force of Nature"),
    ("lamprey", "Lamprey"),
    ("leela_patel_trained_pragmatist", "Leela Patel: Trained Pragmatist"),
    ("hostage", "Hostage"),
    ("spear_phishing", "Spear Phishing"),
    ("hq_interface", "HQ Interface"),
    ("paragon", "Paragon"),
    ("demara", "Demara"),
    ("faerie", "Faerie"),
    ("chaos_theory_wunderkind", "Chaos Theory: Wünderkind"),
    ("notoriety", "Notoriety"),
    ("dinosaurus", "Dinosaurus"),
    ("r_d_interface", "R&D Interface"),
    ("deus_x", "Deus X"),
    ("ice_analyzer", "Ice Analyzer"),
    ("john_masanori", "John Masanori"),
    ("kati_jones", "Kati Jones"),
    ("haas_bioroid_stronger_together", "Haas-Bioroid: Stronger Together"),
    ("seidr_laboratories_destiny_defined", "Seidr Laboratories: Destiny Defined"),
    ("successful_field_test", "Successful Field Test"),
    ("turing", "Turing"),
    ("blue_level_clearance", "Blue Level Clearance"),
    ("ash_2x3zb9cy", "Ash 2X3ZB9CY"),
    ("mason_bellamy", "Mason Bellamy"),
    ("jinteki_replicating_perfection", "Jinteki: Replicating Perfection"),
    ("fetal_ai", "Fetal AI"),
    ("philotic_entanglement", "Philotic Entanglement"),
    ("sundew", "Sundew"),
    ("himitsu_bako", "Himitsu-Bako"),
    ("tsurugi", "Tsurugi"),
    ("yagura", "Yagura"),
    ("spark_agency_worldswide_reach", "Spark Agency: Worldswide Reach"),
    ("explode_a_palooza", "Explode-a-palooza"),
    ("marked_accounts", "Marked Accounts"),
    ("flare", "Flare"),
    ("product_placement", "Product Placement"),
    ("blue_sun_powering_the_future", "Blue Sun: Powering the Future"),
    ("contract_killer", "Contract Killer"),
    ("elizabeth_mills", "Elizabeth Mills"),
    ("public_support", "Public Support"),
    ("caduceus", "Caduceus"),
    ("spiderweb", "Spiderweb"),
    ("oversight_ai", "Oversight AI"),
    ("paper_trail", "Paper Trail"),
    ("ipo", "IPO"),
];
