"""Split the policy head's agreement with the search **by chair**.

    scripts/venv/bin/python3 scripts/policy_head_by_chair.py MODEL CORPUS [--games N] [--json OUT]

`diagnose_policy_head.py` answers "is this head worth anything at all" and
reports one number per metric over both seats. This was written for the
question item 31 left standing (ROADMAP Phase 2 §5): the uniform PUCT search's
own corpus is chair-balanced at 54.8% Corp, seating the priors distilled from
it produces ~65%, so the head was assumed to be failing one seat harder than
the other. **It answers that no** (item 32), and the shape of the answer is why
more than one metric is printed: on a held-out uniform-search corpus the raw
top-1 gap is 7.5 points in the Corp's favour, and the same disagreements cost
the two chairs the *same* amount of the search's opinion.

So the metrics below exist to keep a raw gap from being read as a defect:

- **Lift over chance**, `(top1 - chance) / (1 - chance)`, because the seats do
  not branch alike. Item 14 was read through exactly that confound ("Corp top-1
  agreement is 46.9%, higher than the Runner's").
- **Standardization onto the other chair's difficulty cells** — direct
  standardization over (search max visit share x legal-action count). Nearly
  half the raw top-1 gap is the Runner's decisions being closer, not the head
  being worse at them.
- **Visit-share regret**, `target[search's pick] - target[head's pick]`. Top-1
  scores a coin-flip between two near-tied actions exactly as it scores
  abandoning a 0.9-visit move; regret is the same disagreement priced in the
  search's own currency, and it is the metric that answered the question.
- **KL(search || prior)**, the scalar the distillation objective actually
  minimizes, decomposed into the search's own entropy plus the excess. Only the
  excess is the head's fault.
- **Calibration** of the prior the search consumes, over the
  `MixedPriorEvaluator` mixture `q_eps = (1 - eps) q + eps / |legal|` at each
  eps the epsilon sweep used, so the answer can take the form "this chair wants
  this much uniform" — a per-chair `--candidate-prior-mix` rather than a
  retrain. Under the masked objective both chairs pick `eps = 0`.

**Point it at a corpus generated by the uniform search.** A corpus the model
itself generated is a search seeded with the very priors being scored, and
agreement against it is inflated by about eleven points (77.7%/69.4% on
`iter_002` against 66.0%/58.5% on held-out uniform games).

The legal set is the support of the recorded `policy_target`, exactly as in
`diagnose_policy_head.py`: PUCT expands every legal root edge and 128
simulations over ~7 legal actions covers it, and it is a lower bound in any
case. Steps with a support of one are not decisions; they are counted and
dropped, per chair, because "which chair gets more forced moves" is itself part
of the comparison.

Weights are read straight off the ONNX initializers and the forward pass is
reproduced in numpy, for the reason `diagnose_policy_head.py` gives: no
`onnxruntime` on a machine that only wants to read a checkpoint. Games are
streamed in blocks rather than densified at once — a 2,400-game corpus is
~475k steps and ~4.3 GB of dense observations, and the per-chair statistics
this prints are all accumulable.
"""
import argparse, json, glob, os, sys
import numpy as np
import onnx
from onnx import numpy_helper

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from action_space_segments import SEGMENTS, SIZE as ACTION_SPACE_SIZE

CHAIRS = ((0, "CORP"), (1, "RUNNER"))
EPSILONS = (0.0, 0.25, 0.5, 0.75, 1.0)
CAL_BINS = np.array([0.0, 0.02, 0.05, 0.10, 0.20, 0.35, 0.50, 0.70, 0.85, 1.0])
#: A raw chair gap in top-1 is not yet a claim about the *head*: a seat whose
#: search targets are flatter, or whose decisions branch wider, is harder to
#: imitate for reasons that have nothing to do with what was learned. These are
#: the two axes of that difficulty, and `standardized` reweights one chair
#: onto the other's cells to take both out at once.
PEAK_BINS = np.array([0.0, 0.30, 0.40, 0.50, 0.60, 0.75, 0.90, 1.0001])
LEGAL_BINS = np.array([2, 3, 4, 5, 6, 8, 12, 10_000])


def load_weights(path):
    graph = onnx.load(path).graph
    W = {i.name: numpy_helper.to_array(i) for i in graph.initializer}
    eps = 1e-5
    for node in graph.node:
        if node.op_type == "LayerNormalization":
            eps = next((a.f for a in node.attribute if a.name == "epsilon"), eps)
            break
    return W, eps


def make_forward(W, ln_eps):
    def gemm(x, w, b):              # torch Linear export: Y = X @ W.T + b
        return x @ w.T + b

    def layernorm(x, w, b):
        mu = x.mean(-1, keepdims=True)
        var = x.var(-1, keepdims=True)
        return (x - mu) / np.sqrt(var + ln_eps) * w + b

    def forward(obs):
        h = layernorm(gemm(obs, W["trunk.0.weight"], W["trunk.0.bias"]),
                      W["trunk.1.weight"], W["trunk.1.bias"])
        h = np.maximum(h, 0)
        h = layernorm(gemm(h, W["trunk.3.weight"], W["trunk.3.bias"]),
                      W["trunk.4.weight"], W["trunk.4.bias"])
        h = np.maximum(h, 0)
        p = np.maximum(gemm(h, W["policy_head.0.weight"], W["policy_head.0.bias"]), 0)
        logits = gemm(p, W["policy_head.2.weight"], W["policy_head.2.bias"])
        v = np.maximum(gemm(h, W["value_head.0.weight"], W["value_head.0.bias"]), 0)
        value = np.tanh(gemm(v, W["value_head.2.weight"], W["value_head.2.bias"]))
        return logits, value[:, 0]

    return forward


class ChairStats:
    """Everything accumulated for one seat.

    Per-step scalars are kept as lists rather than summed because the
    interesting cuts (decisive steps, the losing side, the disagreements) are
    conditional means, and a few float64 per step over half a million steps is
    forty megabytes -- cheap next to re-reading the corpus once per cut.
    """

    def __init__(self):
        self.n_forced = 0
        self.n_legal, self.top1, self.chance = [], [], []
        self.kl = {e: [] for e in EPSILONS}
        self.search_entropy, self.excess = [], []
        self.peak, self.tgt_peak, self.on_best, self.regret = [], [], [], []
        self.value_err, self.outcome = [], []
        # [segment, (steps where legal, search mass, model mass)]
        self.segments = np.zeros((len(SEGMENTS), 3))
        # [peak bin, legal-count bin, (steps, top-1 hits, summed regret)] --
        # the difficulty cells `standardized` reweights over.
        self.difficulty = np.zeros((len(PEAK_BINS) - 1, len(LEGAL_BINS) - 1, 3))
        # Reliability over every (step, legal slot) pair, per epsilon:
        # [bin, (pairs, summed prior, summed search visit share)]
        self.calibration = {e: np.zeros((len(CAL_BINS) - 1, 3)) for e in EPSILONS}


def accumulate(stats, sup, tgt, sub_logits, value, outcome_for_side):
    exp = np.exp(sub_logits - sub_logits.max())
    q = exp / exp.sum()
    n = len(sup)
    uniform = 1.0 / n

    best = int(tgt.argmax())
    stats.n_legal.append(n)
    stats.chance.append(uniform)
    stats.top1.append(float(int(q.argmax()) == best))
    stats.peak.append(float(q.max()))
    stats.tgt_peak.append(float(tgt.max()))
    stats.on_best.append(float(q[best]))
    # Visit-share regret: what the search would have spent on its own pick,
    # less what it spent on the head's. Top-1 counts a disagreement between
    # two near-tied actions the same as one that abandons a 0.9-visit move;
    # this is the same quantity in the search's own currency, and it is what
    # makes the two chairs comparable without any further adjustment.
    stats.regret.append(float(tgt[best] - tgt[int(q.argmax())]))
    stats.outcome.append(outcome_for_side)
    stats.value_err.append(float(value - outcome_for_side))

    pb = int(np.clip(np.digitize(tgt.max(), PEAK_BINS) - 1, 0, len(PEAK_BINS) - 2))
    lb = int(np.clip(np.digitize(n, LEGAL_BINS) - 1, 0, len(LEGAL_BINS) - 2))
    stats.difficulty[pb, lb, 0] += 1
    stats.difficulty[pb, lb, 1] += stats.top1[-1]
    stats.difficulty[pb, lb, 2] += stats.regret[-1]

    nonzero = tgt > 0
    h_search = float(-(tgt[nonzero] * np.log(tgt[nonzero])).sum())
    stats.search_entropy.append(h_search)
    for e in EPSILONS:
        mixed = (1.0 - e) * q + e * uniform
        kl = float(-(tgt[nonzero] * np.log(mixed[nonzero] + 1e-12)).sum()) - h_search
        stats.kl[e].append(kl)
        acc = stats.calibration[e]
        which = np.clip(np.digitize(mixed, CAL_BINS) - 1, 0, len(CAL_BINS) - 2)
        np.add.at(acc[:, 0], which, 1.0)
        np.add.at(acc[:, 1], which, mixed)
        np.add.at(acc[:, 2], which, tgt)
    stats.excess.append(stats.kl[0.0][-1])

    for si, (_name, lo, hi) in enumerate(SEGMENTS):
        inside = (sup >= lo) & (sup < hi)
        if inside.any():
            stats.segments[si, 0] += 1
            stats.segments[si, 1] += tgt[inside].sum()
            stats.segments[si, 2] += q[inside].sum()


def read_corpus(paths, obs_size_out, block=4096):
    """Yield blocks of (obs, supports, targets, sides, outcomes) from the corpus.

    `outcome` is +1/-1 from the *acting seat's* point of view, so a Corp step in
    a game the Corp won and a Runner step in a game the Runner won carry the
    same number -- the same convention `train_alpha_netrunner.py` builds
    `outcomes_by_sample` under, which is what the value head was fitted to.
    `outcome_corp` is already signed +-1 in the trajectory (0 only for a stall,
    and stalls are dropped above).
    """
    obs_rows, sups, tgts, sides, outcomes = [], [], [], [], []
    stalled = 0
    for path in paths:
        with open(path) as f:
            game = json.load(f)
        if str(game.get("end_reason", "")).startswith("stall_"):
            stalled += 1
            continue
        if obs_size_out[0] is None:
            obs_size_out[0] = game["observation_size"]
        elif game["observation_size"] != obs_size_out[0]:
            raise SystemExit(f"{path}: observation_size {game['observation_size']} != "
                             f"{obs_size_out[0]}; a corpus must not mix layouts")
        if game["action_space_size"] != ACTION_SPACE_SIZE:
            raise SystemExit(f"{path}: action_space_size {game['action_space_size']} != "
                             f"{ACTION_SPACE_SIZE}; the segment table is for another layout")
        corp_result = float(game["outcome_corp"])
        for st in game["steps"]:
            side = st["active_side"]
            o = np.zeros(obs_size_out[0], dtype=np.float32)
            for i, v in st["observation"]:
                o[i] = v
            obs_rows.append(o)
            sups.append(np.array([i for i, _ in st["policy_target"]], dtype=np.int64))
            tgts.append(np.array([v for _, v in st["policy_target"]], dtype=np.float64))
            sides.append(side)
            outcomes.append(corp_result if side == 0 else -corp_result)
            if len(obs_rows) >= block:
                yield np.stack(obs_rows), sups, tgts, sides, outcomes, stalled
                obs_rows, sups, tgts, sides, outcomes, stalled = [], [], [], [], [], 0
    if obs_rows:
        yield np.stack(obs_rows), sups, tgts, sides, outcomes, stalled


def standardized(subject, reference, channel=1):
    """`subject`'s per-step mean, reweighted onto `reference`'s difficulty cells.

    Direct standardization, the same device as an age-adjusted rate. Cells the
    reference visits and the subject never does are dropped and their weight
    reported, because a silently renormalized denominator is how this kind of
    adjustment lies. Returns `(rate, weight covered)`.
    """
    ref = reference.difficulty[:, :, 0]
    sub_n, sub_hits = subject.difficulty[:, :, 0], subject.difficulty[:, :, channel]
    usable = (ref > 0) & (sub_n > 0)
    weight = ref[usable]
    if weight.sum() == 0:
        return float("nan"), 0.0
    rate = float(np.sum(weight * (sub_hits[usable] / sub_n[usable])) / weight.sum())
    return rate, float(weight.sum() / ref.sum())


def wilson_halfwidth(values):
    values = np.asarray(values, dtype=float)
    return 1.96 * values.std(ddof=1) / np.sqrt(len(values)) if len(values) > 1 else float("nan")


def report(model, corpus, n_games, stats, forced_share, stalled, out_json):
    def line(label, fmt, fn):
        cells = "  ".join(f"{fmt.format(fn(stats[side])):>12s}" for side, _ in CHAIRS)
        print(f"  {label:38s}{cells}")

    print(f"{model}\n  over {corpus}: {n_games} games ({stalled} stalled, dropped)")
    print()
    header = "  ".join(f"{name:>12s}" for _, name in CHAIRS)
    print(f"  {'':38s}{header}")
    line("decision steps", "{:d}", lambda s: len(s.top1))
    line("forced steps (support of 1, dropped)", "{:d}", lambda s: s.n_forced)
    line("mean legal actions", "{:.2f}", lambda s: np.mean(s.n_legal))
    line("search entropy / step (nats)", "{:.3f}", lambda s: np.mean(s.search_entropy))
    line("search max visit share", "{:.3f}", lambda s: np.mean(s.tgt_peak))
    print()
    print("  TOP-1 AGREEMENT WITH THE SEARCH")
    line("top-1", "{:.1%}", lambda s: np.mean(s.top1))
    line("  +-95%", "{:.1%}", lambda s: wilson_halfwidth(s.top1))
    line("chance (uniform over legal)", "{:.1%}", lambda s: np.mean(s.chance))
    line("lift over chance", "{:.3f}",
         lambda s: (np.mean(s.top1) - np.mean(s.chance)) / (1.0 - np.mean(s.chance)))
    dec = lambda s: np.array(s.tgt_peak) > 0.5
    line("top-1 where search is decisive (>.5)", "{:.1%}",
         lambda s: np.mean(np.array(s.top1)[dec(s)]))
    line("  those steps", "{:.1%}", lambda s: dec(s).mean())
    win = lambda s: np.array(s.outcome) > 0
    line("top-1 on the winning side", "{:.1%}",
         lambda s: np.mean(np.array(s.top1)[win(s)]))
    line("top-1 on the losing side", "{:.1%}",
         lambda s: np.mean(np.array(s.top1)[~win(s)]))
    print()
    print("  ...AND WITH DECISION DIFFICULTY TAKEN OUT")
    print("  Each chair's top-1 reweighted onto the *other* chair's cells over")
    print("  (search max visit share x legal-action count). A gap that survives this")
    print("  is the head's; one that does not was the seat's decisions being harder.")
    for side, name in CHAIRS:
        other = 1 - side
        rate, covered = standardized(stats[side], stats[other])
        raw = np.mean(stats[side].top1)
        print(f"    {name:8s} {raw:.1%} raw -> {rate:.1%} on {CHAIRS[other][1]}'s cells "
              f"({covered:.1%} of that chair's weight covered)")
    raw_gap = np.mean(stats[0].top1) - np.mean(stats[1].top1)
    on_corp, _ = standardized(stats[1], stats[0])
    print(f"    raw gap {raw_gap:+.1%};  standardized (Corp - Runner-on-Corp's-cells) "
          f"{np.mean(stats[0].top1) - on_corp:+.1%}")
    print()
    print("  VISIT-SHARE REGRET (what the head's pick costs in the search's currency)")
    line("mean regret / decision", "{:.4f}", lambda s: np.mean(s.regret))
    line("  +-95%", "{:.4f}", lambda s: wilson_halfwidth(s.regret))
    line("  on decisive steps (peak > .5)", "{:.4f}",
         lambda s: np.mean(np.array(s.regret)[dec(s)]))
    reg_on_corp, _ = standardized(stats[1], stats[0], channel=2)
    print(f"    raw gap {np.mean(stats[0].regret) - np.mean(stats[1].regret):+.4f};  "
          f"standardized {np.mean(stats[0].regret) - reg_on_corp:+.4f}  "
          f"(negative = the Runner head throws away more of the search's opinion)")
    print()
    print("  TOP-1 BY HOW DECISIVE THE SEARCH WAS (its max visit share)")
    print(f"    {'peak band':>14s} " + "  ".join(f"{n + ' n':>10s} {n + ' top1':>10s}"
                                                for _, n in CHAIRS))
    for b in range(len(PEAK_BINS) - 1):
        cells = []
        for side, _ in CHAIRS:
            row = stats[side].difficulty[b].sum(axis=0)
            cells.append(f"{int(row[0]):10d} "
                         f"{(row[1] / row[0] if row[0] else float('nan')):10.1%}")
        band = f"{PEAK_BINS[b]:.2f}-{min(PEAK_BINS[b+1], 1.0):.2f}"
        print(f"    {band:>14s} " + "  ".join(cells))
    print()
    print("  THE PRIOR THE SEARCH CONSUMES")
    line("mass on the search's best action", "{:.3f}", lambda s: np.mean(s.on_best))
    line("  ...uniform would give", "{:.3f}", lambda s: np.mean(s.chance))
    line("model max prior", "{:.3f}", lambda s: np.mean(s.peak))
    line("starved (<.02 on the best action)", "{:.1%}",
         lambda s: np.mean(np.array(s.on_best) < 0.02))
    line("when wrong: mass on the right action", "{:.3f}",
         lambda s: np.mean(np.array(s.on_best)[np.array(s.top1) == 0.0]))
    print()
    print("  DISTILLATION LOSS, decomposed (nats/step)")
    line("search entropy (irreducible)", "{:.3f}", lambda s: np.mean(s.search_entropy))
    line("KL(search || prior) (the head's own)", "{:.3f}", lambda s: np.mean(s.excess))
    line("  as a share of the search's entropy", "{:.2f}",
         lambda s: np.mean(s.excess) / np.mean(s.search_entropy))
    print()
    print("  VALUE HEAD (not seated in a priors-only run; recorded for the record)")
    line("mean signed error vs the outcome", "{:+.3f}", lambda s: np.mean(s.value_err))
    line("RMSE", "{:.3f}", lambda s: np.sqrt(np.mean(np.square(s.value_err))))
    print()
    print("  MIXING IN UNIFORM (MixedPriorEvaluator's epsilon), mean KL(search || q_eps)")
    for e in EPSILONS:
        line(f"eps = {e:.2f}", "{:.3f}", lambda s, e=e: np.mean(s.kl[e]))
    print("  the epsilon each chair would pick if the search consumed a calibrated prior:")
    for side, name in CHAIRS:
        s = stats[side]
        best = min(EPSILONS, key=lambda e: np.mean(s.kl[e]))
        print(f"    {name:8s} eps = {best:.2f}  "
              f"(KL {np.mean(s.kl[best]):.3f} against {np.mean(s.kl[0.0]):.3f} at eps = 0)")
    print()
    print("  CALIBRATION of the eps = 0 prior, over every (step, legal slot) pair.")
    print("  `search` is the visit share those slots actually got. Above the prior")
    print("  means the head under-weights that band; below means it over-weights.")
    for side, name in CHAIRS:
        acc = stats[side].calibration[0.0]
        total = acc[:, 0].sum()
        ece = np.sum(acc[:, 0] / total * np.abs(acc[:, 1] - acc[:, 2]) / np.maximum(acc[:, 0], 1))
        print(f"\n    --- {name} ---   ECE {ece:.4f}")
        print(f"    {'prior band':>14s} {'pairs':>9s} {'prior':>8s} {'search':>8s} {'ratio':>7s}")
        for b in range(len(CAL_BINS) - 1):
            pairs, prior_sum, search_sum = acc[b]
            if pairs == 0:
                continue
            prior_mean, search_mean = prior_sum / pairs, search_sum / pairs
            ratio = search_mean / prior_mean if prior_mean > 0 else float("nan")
            band = f"{CAL_BINS[b]:.2f}-{CAL_BINS[b+1]:.2f}"
            print(f"    {band:>14s} {int(pairs):9d} {prior_mean:8.3f} {search_mean:8.3f} {ratio:7.2f}")
    print()
    print("  WHERE THE MASS GOES, per chair, over steps where that segment was legal.")
    print("  `ratio` below 1.0 is the head under-weighting what the search wanted.")
    for side, name in CHAIRS:
        acc = stats[side].segments
        print(f"\n    --- {name} ---")
        print(f"    {'segment':26s} {'slots':>6s} {'steps':>8s} {'search':>8s} {'model':>8s} {'ratio':>7s}")
        for si in np.argsort(-acc[:, 1]):
            steps, search_m, model_m = acc[si]
            # Every segment the search touches, never a top-N: item 14 found
            # SCORE AGENDA at a third only because nothing was hidden.
            if steps == 0 or search_m / max(steps, 1) < 0.005:
                continue
            sname, lo, hi = SEGMENTS[si]
            s_mean, m_mean = search_m / steps, model_m / steps
            ratio = m_mean / s_mean if s_mean > 0 else float("nan")
            print(f"    {sname:26s} {hi - lo:6d} {int(steps):8d} {s_mean:8.3f} {m_mean:8.3f} {ratio:7.2f}")

    if out_json:
        blob = {"model": model, "corpus": corpus, "games": n_games, "stalled": stalled,
                "forced_share": forced_share, "chairs": {}}
        for side, name in CHAIRS:
            s = stats[side]
            blob["chairs"][name] = {
                "steps": len(s.top1), "forced_steps": s.n_forced,
                "mean_legal": float(np.mean(s.n_legal)), "chance": float(np.mean(s.chance)),
                "top1": float(np.mean(s.top1)), "top1_ci95": float(wilson_halfwidth(s.top1)),
                "lift": float((np.mean(s.top1) - np.mean(s.chance)) / (1 - np.mean(s.chance))),
                "top1_decisive": float(np.mean(np.array(s.top1)[dec(s)])),
                "top1_standardized_to_other_chair": standardized(s, stats[1 - side])[0],
                "regret": float(np.mean(s.regret)),
                "regret_ci95": float(wilson_halfwidth(s.regret)),
                "regret_standardized_to_other_chair": standardized(s, stats[1 - side], channel=2)[0],
                "top1_winning": float(np.mean(np.array(s.top1)[win(s)])),
                "top1_losing": float(np.mean(np.array(s.top1)[~win(s)])),
                "on_best": float(np.mean(s.on_best)), "peak": float(np.mean(s.peak)),
                "starved": float(np.mean(np.array(s.on_best) < 0.02)),
                "search_entropy": float(np.mean(s.search_entropy)),
                "kl": {str(e): float(np.mean(s.kl[e])) for e in EPSILONS},
                "value_bias": float(np.mean(s.value_err)),
                "value_rmse": float(np.sqrt(np.mean(np.square(s.value_err)))),
                "segments": {SEGMENTS[si][0]: {"steps": int(s.segments[si, 0]),
                                               "search": float(s.segments[si, 1] / s.segments[si, 0]),
                                               "model": float(s.segments[si, 2] / s.segments[si, 0])}
                             for si in range(len(SEGMENTS)) if s.segments[si, 0] > 0},
            }
        with open(out_json, "w") as f:
            json.dump(blob, f, indent=2)
        print(f"\n  wrote {out_json}")


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("model")
    ap.add_argument("corpus")
    ap.add_argument("--games", type=int, default=0, help="0 = the whole corpus")
    ap.add_argument("--json", default=None)
    args = ap.parse_args()

    paths = sorted(glob.glob(f"{args.corpus}/game_*.jsonl"))
    if args.games:
        paths = paths[:args.games]
    if not paths:
        sys.exit(f"no game_*.jsonl under {args.corpus}")

    W, ln_eps = load_weights(args.model)
    forward = make_forward(W, ln_eps)
    stats = {side: ChairStats() for side, _ in CHAIRS}
    obs_size = [None]
    stalled_total = 0
    for obs, sups, tgts, sides, outcomes, stalled in read_corpus(paths, obs_size):
        stalled_total += stalled
        if obs.shape[1] != W["trunk.0.weight"].shape[1]:
            sys.exit(f"corpus observation_size {obs.shape[1]} != the model's "
                     f"{W['trunk.0.weight'].shape[1]}: a checkpoint cannot read another layout")
        logits, value = forward(obs)
        for k in range(len(sups)):
            s = stats[sides[k]]
            if len(sups[k]) < 2:
                s.n_forced += 1
                continue
            accumulate(s, sups[k], tgts[k], logits[k, sups[k]], float(value[k]), outcomes[k])

    forced = {name: stats[side].n_forced / max(stats[side].n_forced + len(stats[side].top1), 1)
              for side, name in CHAIRS}
    report(args.model, args.corpus, len(paths), stats, forced, stalled_total, args.json)


if __name__ == "__main__":
    main()
